# **Prepayment-Mortgage-Trading-Analysis-and-Prediction**

In [ ]:
import pandas as pd
import plotly.express as px

In [ ]:
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# DATA PREPARATION AND PREPROCESSING:

In [ ]:
pd.set_option('display.max_columns', None)

Load the data

In [ ]:

df1 = pd.read_excel(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/loan_balances.xlsx')

# Display the first few rows of the dataframe
df1.head()

,loan_id,loan_amount,first_payment_date,principal_interest_payment,interest_rate,loan_term,next_payment_due_date,payment_periods_made,current_balance
0,5021364,375000,2021-10-01,1632.03,0.03250,360,2021-10-01,0,375000.0
1,5021367,545000,2021-10-01,2822.06,0.02250,240,2021-10-01,0,545000.0
2,5021369,325000,2021-10-01,1368.47,0.02990,360,2021-10-01,0,325000.0
3,5021371,265000,2021-10-01,1099.47,0.02875,360,2021-10-01,0,265000.0
4,5021372,295000,2021-11-01,1304.19,0.03375,360,2021-11-01,0,295000.0

In [ ]:


df2 = pd.read_excel(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/loan_bids.xlsx')
# Display the first few rows of the dataframe
df2.head()

,loan_id,golden_sachs,storgan_manley,smells_largo,bank_of_americans,pj_logan
0,5021364,102.7500,102.78125,102.84375,102.8125,102.71875
1,5021367,0.0000,0.00000,0.00000,0.0000,0.00000
2,5021369,100.8775,100.84625,100.84625,100.8150,100.84625
3,5021371,101.0650,101.09625,101.15875,101.1275,100.90875
4,5021372,102.9375,103.03125,103.03125,103.0000,102.78125

In [ ]:

# Load the dataset
df3 = pd.read_excel(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/loan_data.xlsx')

# Display the first few rows of the DataFrame with all columns visible
pd.set_option('display.max_columns', None)  # This will display all columns
df3.head()

,loan_id,state_code,county,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,loan_type,loan_purpose,lien_position,reverse_mortgage,open-end_line_of_credit,loan_amount,closing_date,first_payment_date,maturity_date,loan_term,principal_interest_pmt,interest_rate,property_value,total_loan_costs,origition_charges,other_loan_costs,lender_credits,prepayment_pelty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,occupancy_type,manufactured_home,total_units,income_thousands,recurring_monthly_debt,median_fico_score,credit_score_type,aus_type,umbs_code,target_profit
0,5021367,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,545000,2021-08-27,2021-10-01,2041-09-01,240,2816.78,2.250,993257,10736.5,10736.5,0,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,108,4230.0,620,Equifax Beacon 5.0,LP,UMBS 15YR 2.0,27250.0
1,5021373,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,135000,2021-08-31,2021-10-01,2051-09-01,360,585.95,3.250,232439,843.5,526.5,317,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,89,3635.0,620,Experian Fair Isaac,LP,UMBS 30YR 3.0,6750.0
2,5021380,CA,Kern,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,125000,2021-09-01,2021-10-01,2036-09-01,180,853.69,2.875,187519,5450.0,2262.5,3187.5,NaN,NaN,NaN,False,0,0,False,Investment property,False,3,142,5325.0,620,Experian Fair Isaac,LP,UMBS 30YR 2.5,6250.0
3,5021427,NC,Forsyth,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,125000,2021-09-09,2021-10-01,2051-09-01,360,559.68,3.500,156250,2078.3,487.5,1590.8,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,32,1120.0,620,Equifax Beacon 5.0,LP,UMBS 30YR 3.0,6250.0
4,5021446,MA,Middlesex,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,535000,2021-09-11,2021-10-01,2051-09-01,360,2075.19,2.375,858060,27392.0,27392.0,0,NaN,NaN,84.0,False,0,0,False,Primary residence,False,1,122,3864.0,620,Equifax Beacon 5.0,DU,UMBS 30YR 2.0,26750.0

In [ ]:

# Load the dataset
df4 = pd.read_excel(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/loan_status.xlsx')

# Display the first few rows of the DataFrame with all columns visible
pd.set_option('display.max_columns', None)  # This will display all columns
df4.head()

,loan_id,closing_date,file_in_audit,file_audit_complete,file_sent_to_custodian,file_at_custodian
0,5023130,2021-04-01,2021-04-05 19:36:02.972,NaT,NaT,NaT
1,5031773,2021-05-06,2021-05-10 09:07:39.400,2021-05-13 04:58:02.148,2021-05-14 04:58:02.148,NaT
2,5035386,2021-05-12,2021-05-14 16:07:05.664,NaT,NaT,NaT
3,5029192,2021-06-12,NaT,NaT,NaT,NaT
4,5037272,2021-06-23,2021-06-28 09:37:23.762,NaT,NaT,NaT

In [ ]:

# Load the dataset
df5 = pd.read_excel(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/target_profit.xlsx')

# Display the first few rows of the DataFrame with all columns visible
pd.set_option('display.max_columns', None)  # This will display all columns
df5.head()

,loan_id,state_code,county,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,loan_type,loan_purpose,lien_position,reverse_mortgage,open-end_line_of_credit,loan_amount,closing_date,first_payment_date,maturity_date,loan_term,principal_interest_pmt,interest_rate,umbs_code,property_value,total_loan_costs,origition_charges,other_loan_costs,lender_credits,prepayment_pelty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,occupancy_type,manufactured_home,total_units,income_thousands,recurring_monthly_debt,median_fico_score,credit_score_type,aus_type,base_margin,umbs price,trade_margin,Target Profit,Trade Premium,points_and_fees,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,acctual loan revenue,actual profit margin
0,5021367,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,545000,2021-08-27,2021-10-01,2041-09-01,240,2816.78,2.250,UMBS 15YR 2.0,993257,10736.5,10736.5,0,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,108,4230.0,620,Equifax Beacon 5.0,LP,1.05,103.03,0.0303,27250.0,16513.5,10736.5,27250.0,27250.0,0.05,0.0303,umbs_price,16513.5,NaN,NaN
1,5021373,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,135000,2021-08-31,2021-10-01,2051-09-01,360,585.95,3.250,UMBS 30YR 3.0,232439,843.5,526.5,317,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,89,3635.0,620,Experian Fair Isaac,LP,1.05,104.61,0.0461,6750.0,6223.5,526.5,6750.0,6750.0,0.05,0.0461,umbs_price,6223.5,NaN,NaN
2,5021380,CA,Kern,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,125000,2021-09-01,2021-10-01,2036-09-01,180,853.69,2.875,UMBS 30YR 2.5,187519,5450.0,2262.5,3187.5,NaN,NaN,NaN,False,0,0,False,Investment property,False,3,142,5325.0,620,Experian Fair Isaac,LP,1.05,103.19,0.0319,6250.0,3987.5,2262.5,6250.0,6250.0,0.05,0.0319,umbs_price,3987.5,NaN,NaN
3,5021427,NC,Forsyth,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,125000,2021-09-09,2021-10-01,2051-09-01,360,559.68,3.500,UMBS 30YR 3.0,156250,2078.3,487.5,1590.8,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,32,1120.0,620,Equifax Beacon 5.0,LP,1.05,104.61,0.0461,6250.0,5762.5,487.5,6250.0,6250.0,0.05,0.0461,umbs_price,5762.5,NaN,NaN
4,5021446,MA,Middlesex,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,535000,2021-09-11,2021-10-01,2051-09-01,360,2075.19,2.375,UMBS 30YR 2.0,858060,27392.0,27392.0,0,NaN,NaN,84.0,False,0,0,False,Primary residence,False,1,122,3864.0,620,Equifax Beacon 5.0,DU,1.05,99.88,-0.0012,26750.0,-642.0,27392.0,26750.0,26750.0,0.05,-0.0012,umbs_price,-642.0,NaN,NaN

In [ ]:

# Load the dataset
df6= pd.read_excel(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/umbs_prices.xlsx')

# Display the first few rows of the DataFrame with all columns visible
pd.set_option('display.max_columns', None)  # This will display all columns
df6.head()

       umbs_code  umbs_coupon  umbs_term  umbs_price
0  UMBS 30YR 1.0          1.0         30       94.98
1  UMBS 30YR 1.5          1.5         30       97.45
2  UMBS 30YR 2.0          2.0         30       99.88
3  UMBS 30YR 2.5          2.5         30      103.19
4  UMBS 30YR 3.0          3.0         30      104.61

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_id                     5367 non-null   int64
 1   loan_amount                 5367 non-null   int64
 2   first_payment_date          5367 non-null   datetime64[ns]
 3   principal_interest_payment  5367 non-null   float64
 4   interest_rate               5367 non-null   float64
 5   loan_term                   5367 non-null   int64
 6   next_payment_due_date       5367 non-null   datetime64[ns]
 7   payment_periods_made        5367 non-null   int64
 8   current_balance             5367 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(4)
memory usage: 377.5 KB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   loan_id            5367 non-null   int64
 1   golden_sachs       5367 non-null   float64
 2   storgan_manley     5367 non-null   float64
 3   smells_largo       5367 non-null   float64
 4   bank_of_americans  5367 non-null   float64
 5   pj_logan           5367 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 251.7 KB

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   loan_id                       5367 non-null   int64
 1   state_code                    5367 non-null   object
 2   county                        5367 non-null   object
 3   conforming_loan_limit         5367 non-null   bool
 4   derived_loan_product_type     5367 non-null   object
 5   derived_dwelling_category     5367 non-null   object
 6   loan_type                     5367 non-null   object
 7   loan_purpose                  5367 non-null   object
 8   lien_position                 5367 non-null   int64
 9   reverse_mortgage              5367 non-null   bool
 10  open-end_line_of_credit       5367 non-null   bool
 11  loan_amount                   5367 non-null   int64
 12  closing_date                  5367 non-null   datetime64[ns]
 13  first_payment_date            5367 non-null   datetime64[ns]
 14  maturity_date                 5367 non-null   datetime64[ns]
 15  loan_term                     5367 non-null   int64
 16  principal_interest_pmt        5367 non-null   float64
 17  interest_rate                 5367 non-null   float64
 18  property_value                5367 non-null   int64
 19  total_loan_costs              5365 non-null   float64
 20  origition_charges             5367 non-null   float64
 21  other_loan_costs              5367 non-null   object
 22  lender_credits                39 non-null     object
 23  prepayment_pelty_term         0 non-null      float64
 24  intro_rate_period             85 non-null     float64
 25  negative_amortization         5367 non-null   bool
 26  interest_only_payment         5367 non-null   int64
 27  balloon_payment               5367 non-null   int64
 28  other_nonamortizing_features  5367 non-null   bool
 29  occupancy_type                5367 non-null   object
 30  manufactured_home             5367 non-null   bool
 31  total_units                   5367 non-null   int64
 32  income_thousands              5367 non-null   object
 33  recurring_monthly_debt        5340 non-null   float64
 34  median_fico_score             5367 non-null   int64
 35  credit_score_type             5367 non-null   object
 36  aus_type                      5304 non-null   object
 37  umbs_code                     5367 non-null   object
 38  target_profit                 5367 non-null   float64
dtypes: bool(6), datetime64[ns](3), float64(8), int64(9), object(13)
memory usage: 1.4+ MB

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   loan_id                 5367 non-null   int64
 1   closing_date            5367 non-null   datetime64[ns]
 2   file_in_audit           5114 non-null   datetime64[ns]
 3   file_audit_complete     4591 non-null   datetime64[ns]
 4   file_sent_to_custodian  4207 non-null   datetime64[ns]
 5   file_at_custodian       3244 non-null   datetime64[ns]
dtypes: datetime64[ns](5), int64(1)
memory usage: 251.7 KB

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 52 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   loan_id                       5367 non-null   int64
 1   state_code                    5367 non-null   object
 2   county                        5367 non-null   object
 3   conforming_loan_limit         5367 non-null   bool
 4   derived_loan_product_type     5367 non-null   object
 5   derived_dwelling_category     5367 non-null   object
 6   loan_type                     5367 non-null   object
 7   loan_purpose                  5367 non-null   object
 8   lien_position                 5367 non-null   int64
 9   reverse_mortgage              5367 non-null   bool
 10  open-end_line_of_credit       5367 non-null   bool
 11  loan_amount                   5367 non-null   int64
 12  closing_date                  5367 non-null   datetime64[ns]
 13  first_payment_date            5367 non-null   datetime64[ns]
 14  maturity_date                 5367 non-null   datetime64[ns]
 15  loan_term                     5367 non-null   int64
 16  principal_interest_pmt        5367 non-null   float64
 17  interest_rate                 5367 non-null   float64
 18  umbs_code                     5367 non-null   object
 19  property_value                5367 non-null   int64
 20  total_loan_costs              5365 non-null   float64
 21  origition_charges             5367 non-null   float64
 22  other_loan_costs              5367 non-null   object
 23  lender_credits                39 non-null     object
 24  prepayment_pelty_term         0 non-null      float64
 25  intro_rate_period             85 non-null     float64
 26  negative_amortization         5367 non-null   bool
 27  interest_only_payment         5367 non-null   int64
 28  balloon_payment               5367 non-null   int64
 29  other_nonamortizing_features  5367 non-null   bool
 30  occupancy_type                5367 non-null   object
 31  manufactured_home             5367 non-null   bool
 32  total_units                   5367 non-null   int64
 33  income_thousands              5367 non-null   object
 34  recurring_monthly_debt        5340 non-null   float64
 35  median_fico_score             5367 non-null   int64
 36  credit_score_type             5367 non-null   object
 37  aus_type                      5304 non-null   object
 38  base_margin                   5367 non-null   float64
 39  umbs price                    5367 non-null   float64
 40  trade_margin                  5367 non-null   float64
 41  Target Profit                 5367 non-null   float64
 42  Trade Premium                 5367 non-null   float64
 43  points_and_fees               5367 non-null   float64
 44  Total Loan Revenue            5367 non-null   float64
 45  Gross Profit                  5365 non-null   float64
 46  Profit Margin                 5365 non-null   float64
 47  Winning Bid                   5367 non-null   float64
 48  Winner                        5367 non-null   object
 49  actual trade premium          5367 non-null   float64
 50  acctual loan revenue          1467 non-null   float64
 51  actual profit margin          1467 non-null   float64
dtypes: bool(6), datetime64[ns](3), float64(20), int64(9), object(14)
memory usage: 1.9+ MB

In [ ]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   umbs_code    17 non-null     object
 1   umbs_coupon  17 non-null     float64
 2   umbs_term    17 non-null     int64
 3   umbs_price   17 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 672.0+ bytes

### checking null values:

In [ ]:
df1.isna().sum()

loan_id                       0
loan_amount                   0
first_payment_date            0
principal_interest_payment    0
interest_rate                 0
loan_term                     0
next_payment_due_date         0
payment_periods_made          0
current_balance               0
dtype: int64

In [ ]:
df2.isna().sum()

loan_id              0
golden_sachs         0
storgan_manley       0
smells_largo         0
bank_of_americans    0
pj_logan             0
dtype: int64

In [ ]:
df3.isna().sum()

loan_id                            0
state_code                         0
county                             0
conforming_loan_limit              0
derived_loan_product_type          0
derived_dwelling_category          0
loan_type                          0
loan_purpose                       0
lien_position                      0
reverse_mortgage                   0
open-end_line_of_credit            0
loan_amount                        0
closing_date                       0
first_payment_date                 0
maturity_date                      0
loan_term                          0
principal_interest_pmt             0
interest_rate                      0
property_value                     0
total_loan_costs                   2
origition_charges                  0
other_loan_costs                   0
lender_credits                  5328
prepayment_pelty_term           5367
intro_rate_period               5282
negative_amortization              0
interest_only_payment              0
balloon_payment                    0
other_nonamortizing_features       0
occupancy_type                     0
manufactured_home                  0
total_units                        0
income_thousands                   0
recurring_monthly_debt            27
median_fico_score                  0
credit_score_type                  0
aus_type                          63
umbs_code                          0
target_profit                      0
dtype: int64

In [ ]:
df4.isna().sum()

loan_id                      0
closing_date                 0
file_in_audit              253
file_audit_complete        776
file_sent_to_custodian    1160
file_at_custodian         2123
dtype: int64

In [ ]:
df5.isna().sum()

loan_id                            0
state_code                         0
county                             0
conforming_loan_limit              0
derived_loan_product_type          0
derived_dwelling_category          0
loan_type                          0
loan_purpose                       0
lien_position                      0
reverse_mortgage                   0
open-end_line_of_credit            0
loan_amount                        0
closing_date                       0
first_payment_date                 0
maturity_date                      0
loan_term                          0
principal_interest_pmt             0
interest_rate                      0
umbs_code                          0
property_value                     0
total_loan_costs                   2
origition_charges                  0
other_loan_costs                   0
lender_credits                  5328
prepayment_pelty_term           5367
intro_rate_period               5282
negative_amortization              0
interest_only_payment              0
balloon_payment                    0
other_nonamortizing_features       0
occupancy_type                     0
manufactured_home                  0
total_units                        0
income_thousands                   0
recurring_monthly_debt            27
median_fico_score                  0
credit_score_type                  0
aus_type                          63
base_margin                        0
umbs price                         0
trade_margin                       0
Target Profit                      0
Trade Premium                      0
points_and_fees                    0
Total Loan Revenue                 0
Gross Profit                       2
Profit Margin                      2
Winning Bid                        0
Winner                             0
actual trade premium               0
acctual loan revenue            3900
actual profit margin            3900
dtype: int64

In [ ]:
df6.isna().sum()

umbs_code      0
umbs_coupon    0
umbs_term      0
umbs_price     0
dtype: int64

Let's identify the duplicate rows in each dataset

In [ ]:
# Loop through each column and find duplicates
for column in df1.columns:
    duplicates = df1[df1.duplicated(subset=[column], keep=False)]
    if not duplicates.empty:
        print(f"Duplicates in column '{column}':")
        print(duplicates)
    else:
        print(f"No duplicates found in column '{column}'.")

No duplicates found in column 'loan_id'.
Duplicates in column 'loan_amount':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[5348 rows x 9 columns]
Duplicates in column 'first_payment_date':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[5365 rows x 9 columns]
Duplicates in column 'principal_interest_payment':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[4456 rows x 9 columns]
Duplicates in column 'interest_rate':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[5359 rows x 9 columns]
Duplicates in column 'loan_term':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[5366 rows x 9 columns]
Duplicates in column 'next_payment_due_date':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[5364 rows x 9 columns]
Duplicates in column 'payment_periods_made':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[5364 rows x 9 columns]
Duplicates in column 'current_balance':
      loan_id  loan_amount first_payment_date  principal_interest_payment  \
0     5021364       375000         2021-10-01                     1632.03
1     5021367       545000         2021-10-01                     2822.06
2     5021369       325000         2021-10-01                     1368.47
3     5021371       265000         2021-10-01                     1099.47
4     5021372       295000         2021-11-01                     1304.19
...       ...          ...                ...                         ...
5362  5037634       345000         2021-11-01                     1501.47
5363  5037636       215000         2021-10-01                      905.29
5364  5037638       405000         2021-10-01                     1705.32
5365  5037641       255000         2021-10-01                     1057.98
5366  5037646        95000         2021-10-01                      420.00

      interest_rate  loan_term next_payment_due_date  payment_periods_made  \
0           0.03250        360            2021-10-01                     0
1           0.02250        240            2021-10-01                     0
2           0.02990        360            2021-10-01                     0
3           0.02875        360            2021-10-01                     0
4           0.03375        360            2021-11-01                     0
...             ...        ...                   ...                   ...
5362        0.03250        360            2021-11-01                     0
5363        0.02990        360            2021-10-01                     0
5364        0.02990        360            2021-10-01                     0
5365        0.02875        360            2021-10-01                     0
5366        0.03375        360            2021-10-01                     0

      current_balance
0            375000.0
1            545000.0
2            325000.0
3            265000.0
4            295000.0
...               ...
5362         345000.0
5363         215000.0
5364         405000.0
5365         255000.0
5366          95000.0

[5105 rows x 9 columns]

Add a new column 'loan_status' in the loan balances data

In [ ]:
data=df1

In [ ]:
# Convert date columns to datetime
data['first_payment_date'] = pd.to_datetime(data['first_payment_date'], errors='coerce')
data['next_payment_due_date'] = pd.to_datetime(data['next_payment_due_date'], errors='coerce')

# Define loan statuses based on current_balance and next_payment_due_date
def determine_loan_status(row):
    if row['current_balance'] == 0:
        return 'Closed'
    elif row['next_payment_due_date'] < pd.Timestamp('today'):
        return 'Delinquent'
    else:
        return 'Active'

# Apply the function to create the loan_status column
data['loan_status'] = data.apply(determine_loan_status, axis=1)

# Display the distribution of loan statuses
print("Distribution of loan statuses:")
print(data['loan_status'].value_counts())

Distribution of loan statuses:
loan_status
Delinquent    5367
Name: count, dtype: int64

In [ ]:
# Check the distribution and unique values in the next_payment_due_date column
print("Summary statistics of next_payment_due_date:")
print(data['next_payment_due_date'].describe())

print("\nUnique next_payment_due_date values:")
print(data['next_payment_due_date'].unique())

# Display the first few rows to inspect the next_payment_due_date values
print("\nFirst few rows of the dataset:")
print(data[['current_balance', 'next_payment_due_date', 'loan_status']].head())

Summary statistics of next_payment_due_date:
count                             5367
mean     2021-10-07 20:56:28.708775680
min                2021-06-01 00:00:00
25%                2021-10-01 00:00:00
50%                2021-10-01 00:00:00
75%                2021-10-01 00:00:00
max                2022-04-01 00:00:00
Name: next_payment_due_date, dtype: object

Unique next_payment_due_date values:
<DatetimeArray>
['2021-10-01 00:00:00', '2021-11-01 00:00:00', '2021-09-01 00:00:00',
 '2021-12-01 00:00:00', '2021-06-01 00:00:00', '2022-02-01 00:00:00',
 '2022-01-01 00:00:00', '2022-04-01 00:00:00']
Length: 8, dtype: datetime64[ns]

First few rows of the dataset:
   current_balance next_payment_due_date loan_status
0         375000.0            2021-10-01  Delinquent
1         545000.0            2021-10-01  Delinquent
2         325000.0            2021-10-01  Delinquent
3         265000.0            2021-10-01  Delinquent
4         295000.0            2021-11-01  Delinquent

All the loans are considred as delinquent because the next payment due date is in the past relative to today's date (pd.Timestamp('today')).

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_id                     5367 non-null   int64
 1   loan_amount                 5367 non-null   int64
 2   first_payment_date          5367 non-null   datetime64[ns]
 3   principal_interest_payment  5367 non-null   float64
 4   interest_rate               5367 non-null   float64
 5   loan_term                   5367 non-null   int64
 6   next_payment_due_date       5367 non-null   datetime64[ns]
 7   payment_periods_made        5367 non-null   int64
 8   current_balance             5367 non-null   float64
 9   loan_status                 5367 non-null   object
 10  amortized_balance           5367 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(4), object(1)
memory usage: 461.4+ KB

Add a second column 'amortized_balance'

In [ ]:
def calculate_amortized_balance(row):
    # Initialize variables
    principal = row['loan_amount']
    interest_rate = row['interest_rate'] / 100 / 12  # Monthly interest rate
    loan_term = row['loan_term']  # Number of months

    # Calculate monthly payment using the formula for annuity
    monthly_payment = (principal * interest_rate) / (1 - (1 + interest_rate)**-loan_term)

    # Initialize balance with the current balance
    balance = row['current_balance']

    # Calculate amortized balance over the loan term
    for _ in range(loan_term - row['payment_periods_made']):
        interest_payment = balance * interest_rate
        principal_payment = monthly_payment - interest_payment
        balance -= principal_payment

    # Return the final amortized balance
    return balance

# Apply the function to create the amortized_balance column
data['amortized_balance'] = data.apply(calculate_amortized_balance, axis=1)

In [ ]:
data.describe()

,loan_id,loan_amount,first_payment_date,principal_interest_payment,interest_rate,loan_term,next_payment_due_date,payment_periods_made,current_balance,amortized_balance
count,5.367000e+03,5.367000e+03,5367,5367.000000,5367.000000,5367.000000,5367,5367.000000,5.367000e+03,5.367000e+03
mean,5.029434e+06,2.830734e+05,2021-10-05 20:10:35.885969920,1368.267444,0.028909,303.648966,2021-10-07 20:56:28.708775680,0.065772,2.830297e+05,1.907408e+01
min,5.021364e+06,5.500000e+04,2021-05-01 00:00:00,231.590000,0.013750,96.000000,2021-06-01 00:00:00,0.000000,5.483228e+04,-6.974067e-06
25%,5.025407e+06,1.650000e+05,2021-10-01 00:00:00,817.880000,0.027500,240.000000,2021-10-01 00:00:00,0.000000,1.650000e+05,-6.411012e-07
50%,5.029402e+06,2.450000e+05,2021-10-01 00:00:00,1187.590000,0.028750,360.000000,2021-10-01 00:00:00,0.000000,2.450000e+05,6.735513e-08
75%,5.033462e+06,3.550000e+05,2021-10-01 00:00:00,1734.215000,0.031250,360.000000,2021-10-01 00:00:00,0.000000,3.550000e+05,6.035179e-07
max,5.037646e+06,1.795000e+06,2021-11-01 00:00:00,7447.320000,0.043750,360.000000,2022-04-01 00:00:00,6.000000,1.795000e+06,3.007615e+03
std,4.690655e+03,1.693160e+05,NaN,776.833434,0.003915,81.851509,NaN,0.282349,1.692983e+05,9.910595e+01

The amortized_balance column has values that are very close to zero, likely due to the precision issues during iterative calculation.

###  Identify commun columns

In [ ]:
# Convert column names to sets
columns_df3 = set(df3.columns)
columns_df5 = set(df5.columns)

# Find common columns across both DataFrames
common_columns = columns_df3 & columns_df5

# Display the number of common columns
num_common_columns = common_columns
print("Number of common columns:", common_columns)

Number of common columns: {'property_value', 'aus_type', 'origition_charges', 'state_code', 'conforming_loan_limit', 'other_nonamortizing_features', 'intro_rate_period', 'derived_loan_product_type', 'occupancy_type', 'total_loan_costs', 'county', 'umbs_code', 'derived_dwelling_category', 'closing_date', 'other_loan_costs', 'interest_rate', 'interest_only_payment', 'loan_amount', 'principal_interest_pmt', 'loan_type', 'loan_id', 'manufactured_home', 'loan_purpose', 'credit_score_type', 'maturity_date', 'prepayment_pelty_term', 'open-end_line_of_credit', 'median_fico_score', 'total_units', 'lien_position', 'balloon_payment', 'loan_term', 'negative_amortization', 'lender_credits', 'recurring_monthly_debt', 'first_payment_date', 'reverse_mortgage', 'income_thousands'}

As the df3 and df5 contains some similar columns, we firstly want to merge them in one data frame

In [ ]:
# Convert the set of common columns to a list
common_columns_list = list(common_columns)

# Merge the DataFrames on the common columns
merged_df = pd.merge(df3, df5, on=common_columns_list, how='outer')

# Display the first few rows of the merged DataFrame
merged_df.head()

,loan_id,state_code,county,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,loan_type,loan_purpose,lien_position,reverse_mortgage,open-end_line_of_credit,loan_amount,closing_date,first_payment_date,maturity_date,loan_term,principal_interest_pmt,interest_rate,property_value,total_loan_costs,origition_charges,other_loan_costs,lender_credits,prepayment_pelty_term,intro_rate_period,negative_amortization,interest_only_payment,balloon_payment,other_nonamortizing_features,occupancy_type,manufactured_home,total_units,income_thousands,recurring_monthly_debt,median_fico_score,credit_score_type,aus_type,umbs_code,target_profit,base_margin,umbs price,trade_margin,Target Profit,Trade Premium,points_and_fees,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,acctual loan revenue,actual profit margin
0,5021367,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,545000,2021-08-27,2021-10-01,2041-09-01,240,2816.78,2.250,993257,10736.5,10736.5,0,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,108,4230.0,620,Equifax Beacon 5.0,LP,UMBS 15YR 2.0,27250.0,1.05,103.03,0.0303,27250.0,16513.5,10736.5,27250.0,27250.0,0.05,0.0303,umbs_price,16513.5,NaN,NaN
1,5021373,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,135000,2021-08-31,2021-10-01,2051-09-01,360,585.95,3.250,232439,843.5,526.5,317,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,89,3635.0,620,Experian Fair Isaac,LP,UMBS 30YR 3.0,6750.0,1.05,104.61,0.0461,6750.0,6223.5,526.5,6750.0,6750.0,0.05,0.0461,umbs_price,6223.5,NaN,NaN
2,5021380,CA,Kern,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,125000,2021-09-01,2021-10-01,2036-09-01,180,853.69,2.875,187519,5450.0,2262.5,3187.5,NaN,NaN,NaN,False,0,0,False,Investment property,False,3,142,5325.0,620,Experian Fair Isaac,LP,UMBS 30YR 2.5,6250.0,1.05,103.19,0.0319,6250.0,3987.5,2262.5,6250.0,6250.0,0.05,0.0319,umbs_price,3987.5,NaN,NaN
3,5021427,NC,Forsyth,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,125000,2021-09-09,2021-10-01,2051-09-01,360,559.68,3.500,156250,2078.3,487.5,1590.8,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,32,1120.0,620,Equifax Beacon 5.0,LP,UMBS 30YR 3.0,6250.0,1.05,104.61,0.0461,6250.0,5762.5,487.5,6250.0,6250.0,0.05,0.0461,umbs_price,5762.5,NaN,NaN
4,5021446,MA,Middlesex,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,535000,2021-09-11,2021-10-01,2051-09-01,360,2075.19,2.375,858060,27392.0,27392.0,0,NaN,NaN,84.0,False,0,0,False,Primary residence,False,1,122,3864.0,620,Equifax Beacon 5.0,DU,UMBS 30YR 2.0,26750.0,1.05,99.88,-0.0012,26750.0,-642.0,27392.0,26750.0,26750.0,0.05,-0.0012,umbs_price,-642.0,NaN,NaN

In [ ]:
len(merged_df)

5367

In [ ]:
merged_df.columns

Index(['loan_id', 'state_code', 'county', 'conforming_loan_limit',
       'derived_loan_product_type', 'derived_dwelling_category', 'loan_type',
       'loan_purpose', 'lien_position', 'reverse_mortgage',
       'open-end_line_of_credit', 'loan_amount', 'closing_date',
       'first_payment_date', 'maturity_date', 'loan_term',
       'principal_interest_pmt', 'interest_rate', 'property_value',
       'total_loan_costs', 'origition_charges', 'other_loan_costs',
       'lender_credits', 'prepayment_pelty_term', 'intro_rate_period',
       'negative_amortization', 'interest_only_payment', 'balloon_payment',
       'other_nonamortizing_features', 'occupancy_type', 'manufactured_home',
       'total_units', 'income_thousands', 'recurring_monthly_debt',
       'median_fico_score', 'credit_score_type', 'aus_type', 'umbs_code',
       'target_profit', 'base_margin', 'umbs price', 'trade_margin',
       'Target Profit', 'Trade Premium', 'points_and_fees',
       'Total Loan Revenue', 'Gross Profit', 'Profit Margin', 'Winning Bid',
       'Winner', 'actual trade premium', 'acctual loan revenue',
       'actual profit margin'],
      dtype='object')

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 53 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   loan_id                       5367 non-null   int64
 1   state_code                    5367 non-null   object
 2   county                        5367 non-null   object
 3   conforming_loan_limit         5367 non-null   bool
 4   derived_loan_product_type     5367 non-null   object
 5   derived_dwelling_category     5367 non-null   object
 6   loan_type                     5367 non-null   object
 7   loan_purpose                  5367 non-null   object
 8   lien_position                 5367 non-null   int64
 9   reverse_mortgage              5367 non-null   bool
 10  open-end_line_of_credit       5367 non-null   bool
 11  loan_amount                   5367 non-null   int64
 12  closing_date                  5367 non-null   datetime64[ns]
 13  first_payment_date            5367 non-null   datetime64[ns]
 14  maturity_date                 5367 non-null   datetime64[ns]
 15  loan_term                     5367 non-null   int64
 16  principal_interest_pmt        5367 non-null   float64
 17  interest_rate                 5367 non-null   float64
 18  property_value                5367 non-null   int64
 19  total_loan_costs              5365 non-null   float64
 20  origition_charges             5367 non-null   float64
 21  other_loan_costs              5367 non-null   object
 22  lender_credits                39 non-null     object
 23  prepayment_pelty_term         0 non-null      float64
 24  intro_rate_period             85 non-null     float64
 25  negative_amortization         5367 non-null   bool
 26  interest_only_payment         5367 non-null   int64
 27  balloon_payment               5367 non-null   int64
 28  other_nonamortizing_features  5367 non-null   bool
 29  occupancy_type                5367 non-null   object
 30  manufactured_home             5367 non-null   bool
 31  total_units                   5367 non-null   int64
 32  income_thousands              5367 non-null   object
 33  recurring_monthly_debt        5340 non-null   float64
 34  median_fico_score             5367 non-null   int64
 35  credit_score_type             5367 non-null   object
 36  aus_type                      5304 non-null   object
 37  umbs_code                     5367 non-null   object
 38  target_profit                 5367 non-null   float64
 39  base_margin                   5367 non-null   float64
 40  umbs price                    5367 non-null   float64
 41  trade_margin                  5367 non-null   float64
 42  Target Profit                 5367 non-null   float64
 43  Trade Premium                 5367 non-null   float64
 44  points_and_fees               5367 non-null   float64
 45  Total Loan Revenue            5367 non-null   float64
 46  Gross Profit                  5365 non-null   float64
 47  Profit Margin                 5365 non-null   float64
 48  Winning Bid                   5367 non-null   float64
 49  Winner                        5367 non-null   object
 50  actual trade premium          5367 non-null   float64
 51  acctual loan revenue          1467 non-null   float64
 52  actual profit margin          1467 non-null   float64
dtypes: bool(6), datetime64[ns](3), float64(21), int64(9), object(14)
memory usage: 2.0+ MB

In [ ]:
merged_df.isna().sum()

loan_id                            0
state_code                         0
county                             0
conforming_loan_limit              0
derived_loan_product_type          0
derived_dwelling_category          0
loan_type                          0
loan_purpose                       0
lien_position                      0
reverse_mortgage                   0
open-end_line_of_credit            0
loan_amount                        0
closing_date                       0
first_payment_date                 0
maturity_date                      0
loan_term                          0
principal_interest_pmt             0
interest_rate                      0
property_value                     0
total_loan_costs                   2
origition_charges                  0
other_loan_costs                   0
lender_credits                  5328
prepayment_pelty_term           5367
intro_rate_period               5282
negative_amortization              0
interest_only_payment              0
balloon_payment                    0
other_nonamortizing_features       0
occupancy_type                     0
manufactured_home                  0
total_units                        0
income_thousands                   0
recurring_monthly_debt            27
median_fico_score                  0
credit_score_type                  0
aus_type                          63
umbs_code                          0
target_profit                      0
base_margin                        0
umbs price                         0
trade_margin                       0
Target Profit                      0
Trade Premium                      0
points_and_fees                    0
Total Loan Revenue                 0
Gross Profit                       2
Profit Margin                      2
Winning Bid                        0
Winner                             0
actual trade premium               0
acctual loan revenue            3900
actual profit margin            3900
dtype: int64

We notice that there are  many null values on lender_credits ,prepayment_pelty_term and intro_rate_period acctual loan revenue ,actual profit margin

### Checking duplicates:

In [ ]:
# Find duplicates based on all columns
duplicate_rows = merged_df[merged_df.duplicated(keep=False)]

In [ ]:
duplicate_rows

Empty DataFrame
Columns: [loan_id, state_code, county, conforming_loan_limit, derived_loan_product_type, derived_dwelling_category, loan_type, loan_purpose, lien_position, reverse_mortgage, open-end_line_of_credit, loan_amount, closing_date, first_payment_date, maturity_date, loan_term, principal_interest_pmt, interest_rate, property_value, total_loan_costs, origition_charges, other_loan_costs, lender_credits, prepayment_pelty_term, intro_rate_period, negative_amortization, interest_only_payment, balloon_payment, other_nonamortizing_features, occupancy_type, manufactured_home, total_units, income_thousands, recurring_monthly_debt, median_fico_score, credit_score_type, aus_type, umbs_code, target_profit, base_margin, umbs price, trade_margin, Target Profit, Trade Premium, points_and_fees, Total Loan Revenue, Gross Profit, Profit Margin, Winning Bid, Winner, actual trade premium, acctual loan revenue, actual profit margin]
Index: []

In [ ]:
# Get the number of unique values in the 'loan_id' column
unique_loan_ids = merged_df['loan_id'].nunique()

# Get the total number of rows in the DataFrame
total_rows = len(merged_df)

# Check if the number of unique loan_ids is equal to the total number of rows
if unique_loan_ids == total_rows:
    print("loan_id contains unique values.")
else:
    print("loan_id does not contain unique values.")

loan_id contains unique values.

Let's merge this resulted dataframe with other dataframes

In [ ]:
dataframes = [data, df2, df3, df4, merged_df]

# Find common columns across all DataFrames
common_columns_set = set.intersection(*(set(df.columns) for df in dataframes))
common_columns_list = list(common_columns_set)

# Merge all DataFrames step by step
merged_data = dataframes[0]
for df in dataframes[1:]:
    merged_data = pd.merge(merged_data, df, on=common_columns_list, how='outer')

# Display the first few rows of the merged DataFrame
merged_data.head()

,loan_id,loan_amount_x,first_payment_date_x,principal_interest_payment,interest_rate_x,loan_term_x,next_payment_due_date,payment_periods_made,current_balance,loan_status,amortized_balance,golden_sachs,storgan_manley,smells_largo,bank_of_americans,pj_logan,state_code_x,county_x,conforming_loan_limit_x,derived_loan_product_type_x,derived_dwelling_category_x,loan_type_x,loan_purpose_x,lien_position_x,reverse_mortgage_x,open-end_line_of_credit_x,loan_amount_y,closing_date_x,first_payment_date_y,maturity_date_x,loan_term_y,principal_interest_pmt_x,interest_rate_y,property_value_x,total_loan_costs_x,origition_charges_x,other_loan_costs_x,lender_credits_x,prepayment_pelty_term_x,intro_rate_period_x,negative_amortization_x,interest_only_payment_x,balloon_payment_x,other_nonamortizing_features_x,occupancy_type_x,manufactured_home_x,total_units_x,income_thousands_x,recurring_monthly_debt_x,median_fico_score_x,credit_score_type_x,aus_type_x,umbs_code_x,target_profit_x,closing_date_y,file_in_audit,file_audit_complete,file_sent_to_custodian,file_at_custodian,state_code_y,county_y,conforming_loan_limit_y,derived_loan_product_type_y,derived_dwelling_category_y,loan_type_y,loan_purpose_y,lien_position_y,reverse_mortgage_y,open-end_line_of_credit_y,loan_amount,closing_date,first_payment_date,maturity_date_y,loan_term,principal_interest_pmt_y,interest_rate,property_value_y,total_loan_costs_y,origition_charges_y,other_loan_costs_y,lender_credits_y,prepayment_pelty_term_y,intro_rate_period_y,negative_amortization_y,interest_only_payment_y,balloon_payment_y,other_nonamortizing_features_y,occupancy_type_y,manufactured_home_y,total_units_y,income_thousands_y,recurring_monthly_debt_y,median_fico_score_y,credit_score_type_y,aus_type_y,umbs_code_y,target_profit_y,base_margin,umbs price,trade_margin,Target Profit,Trade Premium,points_and_fees,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,acctual loan revenue,actual profit margin
0,5021364,375000,2021-10-01,1632.03,0.03250,360,2021-10-01,0,375000.0,Delinquent,1.502453e-07,102.7500,102.78125,102.84375,102.8125,102.71875,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,375000,2021-09-03,2021-10-01,2051-09-01,360,1627.62,3.250,500067,3104.50,0.0,3104.5,NaN,NaN,NaN,False,0,0,False,Investment property,False,1,147,5145.0,650,Experian Fair Isaac,LP,UMBS 15YR 3.0,18750.0,2021-09-03,2021-09-07 00:01:28.091,2021-09-13 10:23:25.842,2021-09-13 08:51:00.030,2021-09-15 08:51:00.030,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,375000,2021-09-03,2021-10-01,2051-09-01,360,1627.62,3.250,500067,3104.50,0.0,3104.5,NaN,NaN,NaN,False,0,0,False,Investment property,False,1,147,5145.0,650,Experian Fair Isaac,LP,UMBS 15YR 3.0,18750.0,1.05,105.00,0.0500,18750.0,18750.0,0.0,18750.0,18750.0,0.05,0.0500,umbs_price,18750.0,NaN,NaN
1,5021367,545000,2021-10-01,2822.06,0.02250,240,2021-10-01,0,545000.0,Delinquent,-1.267486e-06,0.0000,0.00000,0.00000,0.0000,0.00000,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,545000,2021-08-27,2021-10-01,2041-09-01,240,2816.78,2.250,993257,10736.50,10736.5,0,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,108,4230.0,620,Equifax Beacon 5.0,LP,UMBS 15YR 2.0,27250.0,2021-08-27,2021-09-01 00:59:59.982,2021-09-03 00:59:59.982,2021-09-06 00:59:59.982,2021-09-08 00:59:59.982,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,545000,2021-08-27,2021-10-01,2041-09-01,240,2816.78,2.250,993257,10736.50,10736.5,0,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,108,4230.0,620,Equifax Beacon 5.0,LP,UMBS 15YR 2.0,27250.0,1.05,103.03,0.0303,27250.0,16513.5,10736.5,27250.0,27250.0,0.05,0.0303,umbs_price,16513.5,NaN,NaN
2,5021369,325000,2021-10-01,1368.47,0.02990,360,2021-10-01,0,325000.0,Delinquent,-9.163703e-07,100.8775,100.84625,100.84625,100.8150,100.84625,TX,Travis,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,325000,2021-08-21,2021-10-01,2051-09-01,360,1365.06,2.990,651303,8183.75,5882.5,2301.25,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,362,5732.0,643,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,16250.0,2021-08-21,2021-08-30 15:51:20.402,2021-08-31 15:51:20.402,2021-09-01 15:51:20.402,2021-09-03 15:51:20.402,TX,Travis,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,325000,2021-08-21,2021-10-01,2051-09-01,360,1365.06,2.990,651303,8183.75,5882.5,2301.25,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,362,5732.0,643,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,16250.0,1.05,103.19,0.0319,16250.0,10367.5,5882.5,16250.0,16250.0,0.05,0.0319,umbs_price,10367.5,NaN,NaN
3,5021371,265000,2021-10-01,1099.47,0.02875,360,2021-10-01,0,265000.0,Delinquent,-1.029699e-06,101.0650,101.09625,101.15875,101.1275,100.90875,CA,Fresno,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,265000,2021-09-13,2021-10-01,2051-09-01,360,1096.84,2.875,1257713,6814.75,4796.5,2018.25,NaN,NaN,NaN,False,0,0,False,Second residence,False,1,127,4869.0,655,FICO Risk Score Classic,LP,UMBS 30YR 2.5,13250.0,2021-09-13,2021-09-15 11:11:22.061,2021-09-17 11:11:22.061,2021-09-20 11:11:22.061,NaT,CA,Fresno,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,265000,2021-09-13,2021-10-01,2051-09-01,360,1096.84,2.875,1257713,6814.75,4796.5,2018.25,NaN,NaN,NaN,False,0,0,False,Second residence,False,1,127,4869.0,655,FICO Risk Score Classic,LP,UMBS 30YR 2.5,13250.0,1.05,103.19,0.0319,13250.0,8453.5,4796.5,13250.0,13250.0,0.05,0.0319,umbs_price,8453.5,NaN,NaN
4,5021372,295000,2021-11-01,1304.19,0.03375,360,2021-11-01,0,295000.0,Delinquent,4.787354e-07,102.9375,103.03125,103.03125,103.0000,102.78125,NC,Yadkin,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,295000,2021-09-15,2021-11-01,2051-10-01,360,1300.53,3.375,368750,1834.12,0.0,1834.12,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,110,2934.0,655,Equifax Beacon 5.0,DU,UMBS 15YR 3.0,14750.0,2021-09-15,2021-09-20 04:50:24.776,2021-09-21 04:50:24.776,NaT,NaT,NC,Yadkin,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,295000,2021-09-15,2021-11-01,2051-10-01,360,1300.53,3.375,368750,1834.12,0.0,1834.12,NaN,NaN,NaN,False,0,0,False,Primary residence,False,1,110,2934.0,655,Equifax Beacon 5.0,DU,UMBS 15YR 3.0,14750.0,1.05,105.00,0.0500,14750.0,14750.0,0.0,14750.0,14750.0,0.05,0.0500,umbs_price,14750.0,NaN,NaN

We can clearly see that there some added columns that finish with _x or _y. This due to outer operator  that includes all columns from all datasets.

In [ ]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Columns: 111 entries, loan_id to actual profit margin
dtypes: bool(12), datetime64[ns](13), float64(38), int64(20), object(28)
memory usage: 4.1+ MB

We want remove the identical columns and keep the diffrent ones.

In [ ]:
# Identify columns ending with _x and _y
columns_x = [col for col in merged_data.columns if col.endswith('_x')]
columns_y = [col for col in merged_data.columns if col.endswith('_y')]

# Ensure there is a corresponding _y column for each _x column
columns_y_matching = [col[:-2] + '_y' for col in columns_x if col[:-2] + '_y' in columns_y]

# Compare each pair of columns
comparison_results = {}
for col_x in columns_x:
    col_y = col_x[:-2] + '_y'
    if col_y in columns_y_matching:
        comparison_results[col_x] = merged_data[col_x].equals(merged_data[col_y])

# Print comparison results
for col_x, is_equal in comparison_results.items():
    col_y = col_x[:-2] + '_y'
    print(f"Columns {col_x} and {col_y} are {'identical' if is_equal else 'different'}.")

#to see where the differences are
for col_x in columns_x:
    col_y = col_x[:-2] + '_y'
    if col_y in columns_y_matching:
        differences = merged_data[col_x] != merged_data[col_y]
        if differences.any():
            print(f"Differences found in columns {col_x} and {col_y}:")
            print(merged_data[differences][[col_x, col_y]])

Columns loan_amount_x and loan_amount_y are identical.
Columns first_payment_date_x and first_payment_date_y are identical.
Columns interest_rate_x and interest_rate_y are different.
Columns loan_term_x and loan_term_y are identical.
Columns state_code_x and state_code_y are identical.
Columns county_x and county_y are identical.
Columns conforming_loan_limit_x and conforming_loan_limit_y are identical.
Columns derived_loan_product_type_x and derived_loan_product_type_y are identical.
Columns derived_dwelling_category_x and derived_dwelling_category_y are identical.
Columns loan_type_x and loan_type_y are identical.
Columns loan_purpose_x and loan_purpose_y are identical.
Columns lien_position_x and lien_position_y are identical.
Columns reverse_mortgage_x and reverse_mortgage_y are identical.
Columns open-end_line_of_credit_x and open-end_line_of_credit_y are identical.
Columns closing_date_x and closing_date_y are identical.
Columns maturity_date_x and maturity_date_y are identical.
Columns principal_interest_pmt_x and principal_interest_pmt_y are identical.
Columns property_value_x and property_value_y are identical.
Columns total_loan_costs_x and total_loan_costs_y are identical.
Columns origition_charges_x and origition_charges_y are identical.
Columns other_loan_costs_x and other_loan_costs_y are identical.
Columns lender_credits_x and lender_credits_y are identical.
Columns prepayment_pelty_term_x and prepayment_pelty_term_y are identical.
Columns intro_rate_period_x and intro_rate_period_y are identical.
Columns negative_amortization_x and negative_amortization_y are identical.
Columns interest_only_payment_x and interest_only_payment_y are identical.
Columns balloon_payment_x and balloon_payment_y are identical.
Columns other_nonamortizing_features_x and other_nonamortizing_features_y are identical.
Columns occupancy_type_x and occupancy_type_y are identical.
Columns manufactured_home_x and manufactured_home_y are identical.
Columns total_units_x and total_units_y are identical.
Columns income_thousands_x and income_thousands_y are identical.
Columns recurring_monthly_debt_x and recurring_monthly_debt_y are identical.
Columns median_fico_score_x and median_fico_score_y are identical.
Columns credit_score_type_x and credit_score_type_y are identical.
Columns aus_type_x and aus_type_y are identical.
Columns umbs_code_x and umbs_code_y are identical.
Columns target_profit_x and target_profit_y are identical.
Differences found in columns interest_rate_x and interest_rate_y:
      interest_rate_x  interest_rate_y
0             0.03250            3.250
1             0.02250            2.250
2             0.02990            2.990
3             0.02875            2.875
4             0.03375            3.375
...               ...              ...
5362          0.03250            3.250
5363          0.02990            2.990
5364          0.02990            2.990
5365          0.02875            2.875
5366          0.03375            3.375

[5367 rows x 2 columns]
Differences found in columns total_loan_costs_x and total_loan_costs_y:
      total_loan_costs_x  total_loan_costs_y
171                  NaN                 NaN
2507                 NaN                 NaN
Differences found in columns lender_credits_x and lender_credits_y:
     lender_credits_x lender_credits_y
0                 NaN              NaN
1                 NaN              NaN
2                 NaN              NaN
3                 NaN              NaN
4                 NaN              NaN
...               ...              ...
5362              NaN              NaN
5363              NaN              NaN
5364              NaN              NaN
5365              NaN              NaN
5366              NaN              NaN

[5328 rows x 2 columns]
Differences found in columns prepayment_pelty_term_x and prepayment_pelty_term_y:
      prepayment_pelty_term_x  prepayment_pelty_term_y
0                         NaN                      NaN
1                         NaN                      NaN
2                         NaN                      NaN
3                         NaN                      NaN
4                         NaN                      NaN
...                       ...                      ...
5362                      NaN                      NaN
5363                      NaN                      NaN
5364                      NaN                      NaN
5365                      NaN                      NaN
5366                      NaN                      NaN

[5367 rows x 2 columns]
Differences found in columns intro_rate_period_x and intro_rate_period_y:
      intro_rate_period_x  intro_rate_period_y
0                     NaN                  NaN
1                     NaN                  NaN
2                     NaN                  NaN
3                     NaN                  NaN
4                     NaN                  NaN
...                   ...                  ...
5362                  NaN                  NaN
5363                  NaN                  NaN
5364                  NaN                  NaN
5365                  NaN                  NaN
5366                  NaN                  NaN

[5282 rows x 2 columns]
Differences found in columns recurring_monthly_debt_x and recurring_monthly_debt_y:
      recurring_monthly_debt_x  recurring_monthly_debt_y
711                        NaN                       NaN
918                        NaN                       NaN
937                        NaN                       NaN
1225                       NaN                       NaN
1332                       NaN                       NaN
1399                       NaN                       NaN
1504                       NaN                       NaN
1834                       NaN                       NaN
1950                       NaN                       NaN
2060                       NaN                       NaN
2242                       NaN                       NaN
2377                       NaN                       NaN
2655                       NaN                       NaN
2782                       NaN                       NaN
2785                       NaN                       NaN
2866                       NaN                       NaN
3088                       NaN                       NaN
3098                       NaN                       NaN
3142                       NaN                       NaN
3446                       NaN                       NaN
4285                       NaN                       NaN
4448                       NaN                       NaN
4541                       NaN                       NaN
4573                       NaN                       NaN
4698                       NaN                       NaN
4852                       NaN                       NaN
5324                       NaN                       NaN
Differences found in columns aus_type_x and aus_type_y:
     aus_type_x aus_type_y
31          NaN        NaN
110         NaN        NaN
132         NaN        NaN
171         NaN        NaN
188         NaN        NaN
...         ...        ...
5021        NaN        NaN
5193        NaN        NaN
5226        NaN        NaN
5254        NaN        NaN
5349        NaN        NaN

[63 rows x 2 columns]

In [ ]:
# Compare all columns in the DataFrame
all_columns = merged_data.columns
comparison_results_all = {}

# Track groups of identical columns
identical_columns_groups = []

# Compare each column with all other columns
for i, col in enumerate(all_columns):
    if any(col in group for group in identical_columns_groups):
        continue  # Skip columns already in an identical group

    identical_group = [col]
    for other_col in all_columns[i+1:]:
        if merged_data[col].equals(merged_data[other_col]):
            identical_group.append(other_col)

    if len(identical_group) > 1:
        identical_columns_groups.append(identical_group)
        print(f"Columns {', '.join(identical_group)} are identical.")
    else:
        for other_col in all_columns[i+1:]:
            if not merged_data[col].equals(merged_data[other_col]):
                print(f"Columns {col} and {other_col} are different.")
                # Find and print differences for these columns
                differences = merged_data[col] != merged_data[other_col]
                if differences.any():
                    print(f"Differences found in columns {col} and {other_col}:")
                    print(merged_data[differences][[col, other_col]])

# Drop all but one of each group of identical columns
columns_to_drop = {col for group in identical_columns_groups for col in group[1:]}
merged_data.drop(columns=list(columns_to_drop), inplace=True)

# Print final DataFrame columns after dropping identical columns
print("Final columns after dropping identical columns:")
print(merged_data.columns)

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
4     102.78125                110
...         ...                ...
5362  102.89125                 86
5363  103.31500                 58
5364  102.94000                 56
5365  101.53375                110
5366  105.46875                 65

[5367 rows x 2 columns]
Columns pj_logan and recurring_monthly_debt_y are different.
Differences found in columns pj_logan and recurring_monthly_debt_y:
       pj_logan  recurring_monthly_debt_y
0     102.71875                    5145.0
1       0.00000                    4230.0
2     100.84625                    5732.0
3     100.90875                    4869.0
4     102.78125                    2934.0
...         ...                       ...
5362  102.89125                    2724.0
5363  103.31500                    1982.0
5364  102.94000                    2287.0
5365  101.53375                    2934.0
5366  105.46875                    1571.0

[5367 rows x 2 columns]
Columns pj_logan and median_fico_score_y are different.
Differences found in columns pj_logan and median_fico_score_y:
       pj_logan  median_fico_score_y
0     102.71875                  650
1       0.00000                  620
2     100.84625                  643
3     100.90875                  655
4     102.78125                  655
...         ...                  ...
5362  102.89125                  686
5363  103.31500                  709
5364  102.94000                  703
5365  101.53375                  766
5366  105.46875                  766

[5367 rows x 2 columns]
Columns pj_logan and credit_score_type_y are different.
Differences found in columns pj_logan and credit_score_type_y:
       pj_logan      credit_score_type_y
0     102.71875      Experian Fair Isaac
1       0.00000       Equifax Beacon 5.0
2     100.84625       Equifax Beacon 5.0
3     100.90875  FICO Risk Score Classic
4     102.78125       Equifax Beacon 5.0
...         ...                      ...
5362  102.89125  FICO Risk Score Classic
5363  103.31500      Experian Fair Isaac
5364  102.94000      Experian Fair Isaac
5365  101.53375       Equifax Beacon 5.0
5366  105.46875       Equifax Beacon 5.0

[5367 rows x 2 columns]
Columns pj_logan and aus_type_y are different.
Differences found in columns pj_logan and aus_type_y:
       pj_logan aus_type_y
0     102.71875         LP
1       0.00000         LP
2     100.84625         LP
3     100.90875         LP
4     102.78125         DU
...         ...        ...
5362  102.89125         DU
5363  103.31500         LP
5364  102.94000         LP
5365  101.53375         LP
5366  105.46875         LP

[5367 rows x 2 columns]
Columns pj_logan and umbs_code_y are different.
Differences found in columns pj_logan and umbs_code_y:
       pj_logan    umbs_code_y
0     102.71875  UMBS 15YR 3.0
1       0.00000  UMBS 15YR 2.0
2     100.84625  UMBS 30YR 2.5
3     100.90875  UMBS 30YR 2.5
4     102.78125  UMBS 15YR 3.0
...         ...            ...
5362  102.89125  UMBS 30YR 3.0
5363  103.31500  UMBS 30YR 2.5
5364  102.94000  UMBS 30YR 2.5
5365  101.53375  UMBS 30YR 2.5
5366  105.46875  UMBS 15YR 3.0

[5367 rows x 2 columns]
Columns pj_logan and target_profit_y are different.
Differences found in columns pj_logan and target_profit_y:
       pj_logan  target_profit_y
0     102.71875          18750.0
1       0.00000          27250.0
2     100.84625          16250.0
3     100.90875          13250.0
4     102.78125          14750.0
...         ...              ...
5362  102.89125          17250.0
5363  103.31500          10750.0
5364  102.94000          20250.0
5365  101.53375          12750.0
5366  105.46875           4750.0

[5367 rows x 2 columns]
Columns pj_logan and base_margin are different.
Differences found in columns pj_logan and base_margin:
       pj_logan  base_margin
0     102.71875         1.05
1       0.00000         1.05
2     100.84625         1.05
3     100.90875         1.05
4     102.78125         1.05
...         ...          ...
5362  102.89125         1.05
5363  103.31500         1.05
5364  102.94000         1.05
5365  101.53375         1.05
5366  105.46875         1.05

[5367 rows x 2 columns]
Columns pj_logan and umbs price are different.
Differences found in columns pj_logan and umbs price:
       pj_logan  umbs price
0     102.71875      105.00
1       0.00000      103.03
2     100.84625      103.19
3     100.90875      103.19
4     102.78125      105.00
...         ...         ...
5362  102.89125      104.61
5363  103.31500      103.19
5364  102.94000      103.19
5365  101.53375      103.19
5366  105.46875      105.00

[5323 rows x 2 columns]
Columns pj_logan and trade_margin are different.
Differences found in columns pj_logan and trade_margin:
       pj_logan  trade_margin
0     102.71875        0.0500
1       0.00000        0.0303
2     100.84625        0.0319
3     100.90875        0.0319
4     102.78125        0.0500
...         ...           ...
5362  102.89125        0.0461
5363  103.31500        0.0319
5364  102.94000        0.0319
5365  101.53375        0.0319
5366  105.46875        0.0500

[5367 rows x 2 columns]
Columns pj_logan and Target Profit are different.
Differences found in columns pj_logan and Target Profit:
       pj_logan  Target Profit
0     102.71875        18750.0
1       0.00000        27250.0
2     100.84625        16250.0
3     100.90875        13250.0
4     102.78125        14750.0
...         ...            ...
5362  102.89125        17250.0
5363  103.31500        10750.0
5364  102.94000        20250.0
5365  101.53375        12750.0
5366  105.46875         4750.0

[5367 rows x 2 columns]
Columns pj_logan and Trade Premium are different.
Differences found in columns pj_logan and Trade Premium:
       pj_logan  Trade Premium
0     102.71875        18750.0
1       0.00000        16513.5
2     100.84625        10367.5
3     100.90875         8453.5
4     102.78125        14750.0
...         ...            ...
5362  102.89125        15904.5
5363  103.31500         6858.5
5364  102.94000        12919.5
5365  101.53375         8134.5
5366  105.46875         4750.0

[5367 rows x 2 columns]
Columns pj_logan and points_and_fees are different.
Differences found in columns pj_logan and points_and_fees:
       pj_logan  points_and_fees
0     102.71875              0.0
1       0.00000          10736.5
2     100.84625           5882.5
3     100.90875           4796.5
4     102.78125              0.0
...         ...              ...
5362  102.89125           1345.5
5363  103.31500           3891.5
5364  102.94000           7330.5
5365  101.53375           4615.5
5366  105.46875              0.0

[5356 rows x 2 columns]
Columns pj_logan and Total Loan Revenue are different.
Differences found in columns pj_logan and Total Loan Revenue:
       pj_logan  Total Loan Revenue
0     102.71875             18750.0
1       0.00000             27250.0
2     100.84625             16250.0
3     100.90875             13250.0
4     102.78125             14750.0
...         ...                 ...
5362  102.89125             17250.0
5363  103.31500             10750.0
5364  102.94000             20250.0
5365  101.53375             12750.0
5366  105.46875              4750.0

[5367 rows x 2 columns]
Columns pj_logan and Gross Profit are different.
Differences found in columns pj_logan and Gross Profit:
       pj_logan  Gross Profit
0     102.71875       18750.0
1       0.00000       27250.0
2     100.84625       16250.0
3     100.90875       13250.0
4     102.78125       14750.0
...         ...           ...
5362  102.89125       17250.0
5363  103.31500       10750.0
5364  102.94000       20250.0
5365  101.53375       12750.0
5366  105.46875        4750.0

[5367 rows x 2 columns]
Columns pj_logan and Profit Margin are different.
Differences found in columns pj_logan and Profit Margin:
       pj_logan  Profit Margin
0     102.71875           0.05
1       0.00000           0.05
2     100.84625           0.05
3     100.90875           0.05
4     102.78125           0.05
...         ...            ...
5362  102.89125           0.05
5363  103.31500           0.05
5364  102.94000           0.05
5365  101.53375           0.05
5366  105.46875           0.05

[5367 rows x 2 columns]
Columns pj_logan and Winning Bid are different.
Differences found in columns pj_logan and Winning Bid:
       pj_logan  Winning Bid
0     102.71875     0.050000
1       0.00000     0.030300
2     100.84625     0.031900
3     100.90875     0.031900
4     102.78125     0.050000
...         ...          ...
5362  102.89125     0.046100
5363  103.31500     0.034087
5364  102.94000     0.031900
5365  101.53375     0.031900
5366  105.46875     0.054688

[5367 rows x 2 columns]
Columns pj_logan and Winner are different.
Differences found in columns pj_logan and Winner:
       pj_logan        Winner
0     102.71875    umbs_price
1       0.00000    umbs_price
2     100.84625    umbs_price
3     100.90875    umbs_price
4     102.78125    umbs_price
...         ...           ...
5362  102.89125    umbs_price
5363  103.31500  golden_sachs
5364  102.94000    umbs_price
5365  101.53375    umbs_price
5366  105.46875      pj_logan

[5367 rows x 2 columns]
Columns pj_logan and actual trade premium are different.
Differences found in columns pj_logan and actual trade premium:
       pj_logan  actual trade premium
0     102.71875            18750.0000
1       0.00000            16513.5000
2     100.84625            10367.5000
3     100.90875             8453.5000
4     102.78125            14750.0000
...         ...                   ...
5362  102.89125            15904.5000
5363  103.31500             7328.8125
5364  102.94000            12919.5000
5365  101.53375             8134.5000
5366  105.46875             5195.3125

[5367 rows x 2 columns]
Columns pj_logan and acctual loan revenue are different.
Differences found in columns pj_logan and acctual loan revenue:
       pj_logan  acctual loan revenue
0     102.71875                   NaN
1       0.00000                   NaN
2     100.84625                   NaN
3     100.90875                   NaN
4     102.78125                   NaN
...         ...                   ...
5362  102.89125                   NaN
5363  103.31500            11220.3125
5364  102.94000                   NaN
5365  101.53375                   NaN
5366  105.46875             5195.3125

[5367 rows x 2 columns]
Columns pj_logan and actual profit margin are different.
Differences found in columns pj_logan and actual profit margin:
       pj_logan  actual profit margin
0     102.71875                   NaN
1       0.00000                   NaN
2     100.84625                   NaN
3     100.90875                   NaN
4     102.78125                   NaN
...         ...                   ...
5362  102.89125                   NaN
5363  103.31500              0.052187
5364  102.94000                   NaN
5365  101.53375                   NaN
5366  105.46875              0.054688

[5367 rows x 2 columns]
Columns state_code_x, state_code_y are identical.
Columns county_x, county_y are identical.
Columns conforming_loan_limit_x, conforming_loan_limit_y are identical.
Columns derived_loan_product_type_x, derived_loan_product_type_y are identical.
Columns derived_dwelling_category_x, derived_dwelling_category_y are identical.
Columns loan_type_x, loan_type_y are identical.
Columns loan_purpose_x, loan_purpose_y are identical.
Columns lien_position_x, lien_position_y are identical.
Columns reverse_mortgage_x, negative_amortization_x, other_nonamortizing_features_x, manufactured_home_x, reverse_mortgage_y, negative_amortization_y, other_nonamortizing_features_y, manufactured_home_y are identical.
Columns open-end_line_of_credit_x, open-end_line_of_credit_y are identical.
Columns closing_date_x, closing_date_y, closing_date are identical.
Columns maturity_date_x, maturity_date_y are identical.
Columns principal_interest_pmt_x, principal_interest_pmt_y are identical.
Columns interest_rate_y, interest_rate are identical.
Columns property_value_x, property_value_y are identical.
Columns total_loan_costs_x, total_loan_costs_y are identical.
Columns origition_charges_x, origition_charges_y, points_and_fees are identical.
Columns other_loan_costs_x, other_loan_costs_y are identical.
Columns lender_credits_x, lender_credits_y are identical.
Columns prepayment_pelty_term_x, prepayment_pelty_term_y are identical.
Columns intro_rate_period_x, intro_rate_period_y are identical.
Columns interest_only_payment_x, balloon_payment_x, interest_only_payment_y, balloon_payment_y are identical.
Columns occupancy_type_x, occupancy_type_y are identical.
Columns total_units_x, total_units_y are identical.
Columns income_thousands_x, income_thousands_y are identical.
Columns recurring_monthly_debt_x, recurring_monthly_debt_y are identical.
Columns median_fico_score_x, median_fico_score_y are identical.
Columns credit_score_type_x, credit_score_type_y are identical.
Columns aus_type_x, aus_type_y are identical.
Columns umbs_code_x, umbs_code_y are identical.
Columns target_profit_x, target_profit_y, Target Profit are identical.
Columns file_in_audit and file_audit_complete are different.
Differences found in columns file_in_audit and file_audit_complete:
               file_in_audit     file_audit_complete
0    2021-09-07 00:01:28.091 2021-09-13 10:23:25.842
1    2021-09-01 00:59:59.982 2021-09-03 00:59:59.982
2    2021-08-30 15:51:20.402 2021-08-31 15:51:20.402
3    2021-09-15 11:11:22.061 2021-09-17 11:11:22.061
4    2021-09-20 04:50:24.776 2021-09-21 04:50:24.776
...                      ...                     ...
5362 2021-09-20 22:48:28.670                     NaT
5363 2021-08-30 12:06:55.006 2021-09-01 05:34:00.024
5364 2021-09-10 04:10:35.374 2021-09-13 04:10:35.374
5365 2021-09-06 00:00:00.000 2021-09-06 13:38:01.223
5366 2021-09-06 06:35:03.088 2021-09-08 06:35:03.088

[4970 rows x 2 columns]
Columns file_in_audit and file_sent_to_custodian are different.
Differences found in columns file_in_audit and file_sent_to_custodian:
               file_in_audit  file_sent_to_custodian
0    2021-09-07 00:01:28.091 2021-09-13 08:51:00.030
1    2021-09-01 00:59:59.982 2021-09-06 00:59:59.982
2    2021-08-30 15:51:20.402 2021-09-01 15:51:20.402
3    2021-09-15 11:11:22.061 2021-09-20 11:11:22.061
4    2021-09-20 04:50:24.776                     NaT
...                      ...                     ...
5362 2021-09-20 22:48:28.670                     NaT
5363 2021-08-30 12:06:55.006 2021-09-02 05:34:00.024
5364 2021-09-10 04:10:35.374 2021-09-13 04:10:35.374
5365 2021-09-06 00:00:00.000 2021-09-07 13:38:01.223
5366 2021-09-06 06:35:03.088 2021-09-09 06:35:03.088

[5367 rows x 2 columns]
Columns file_in_audit and file_at_custodian are different.
Differences found in columns file_in_audit and file_at_custodian:
               file_in_audit       file_at_custodian
0    2021-09-07 00:01:28.091 2021-09-15 08:51:00.030
1    2021-09-01 00:59:59.982 2021-09-08 00:59:59.982
2    2021-08-30 15:51:20.402 2021-09-03 15:51:20.402
3    2021-09-15 11:11:22.061                     NaT
4    2021-09-20 04:50:24.776                     NaT
...                      ...                     ...
5362 2021-09-20 22:48:28.670                     NaT
5363 2021-08-30 12:06:55.006 2021-09-06 05:34:00.024
5364 2021-09-10 04:10:35.374 2021-09-15 04:10:35.374
5365 2021-09-06 00:00:00.000 2021-09-09 13:38:01.223
5366 2021-09-06 06:35:03.088 2021-09-13 06:35:03.088

[5367 rows x 2 columns]
Columns file_in_audit and state_code_y are different.
Differences found in columns file_in_audit and state_code_y:
               file_in_audit state_code_y
0    2021-09-07 00:01:28.091           CA
1    2021-09-01 00:59:59.982           CA
2    2021-08-30 15:51:20.402           TX
3    2021-09-15 11:11:22.061           CA
4    2021-09-20 04:50:24.776           NC
...                      ...          ...
5362 2021-09-20 22:48:28.670           MA
5363 2021-08-30 12:06:55.006           FL
5364 2021-09-10 04:10:35.374           CA
5365 2021-09-06 00:00:00.000           FL
5366 2021-09-06 06:35:03.088           AR

[5367 rows x 2 columns]
Columns file_in_audit and county_y are different.
Differences found in columns file_in_audit and county_y:
               file_in_audit          county_y
0    2021-09-07 00:01:28.091          Lake
1    2021-09-01 00:59:59.982    Los Angeles
2    2021-08-30 15:51:20.402        Travis
3    2021-09-15 11:11:22.061        Fresno
4    2021-09-20 04:50:24.776        Yadkin
...                      ...               ...
5362 2021-09-20 22:48:28.670       Norfolk
5363 2021-08-30 12:06:55.006       Osceola
5364 2021-09-10 04:10:35.374  Santa Barbara
5365 2021-09-06 00:00:00.000        Miami-Dade
5366 2021-09-06 06:35:03.088     Sebastian

[5367 rows x 2 columns]
Columns file_in_audit and conforming_loan_limit_y are different.
Differences found in columns file_in_audit and conforming_loan_limit_y:
               file_in_audit  conforming_loan_limit_y
0    2021-09-07 00:01:28.091                     True
1    2021-09-01 00:59:59.982                     True
2    2021-08-30 15:51:20.402                     True
3    2021-09-15 11:11:22.061                     True
4    2021-09-20 04:50:24.776                     True
...                      ...                      ...
5362 2021-09-20 22:48:28.670                     True
5363 2021-08-30 12:06:55.006                     True
5364 2021-09-10 04:10:35.374                     True
5365 2021-09-06 00:00:00.000                     True
5366 2021-09-06 06:35:03.088                     True

[5367 rows x 2 columns]
Columns file_in_audit and derived_loan_product_type_y are different.
Differences found in columns file_in_audit and derived_loan_product_type_y:
               file_in_audit derived_loan_product_type_y
0    2021-09-07 00:01:28.091     Conventional:First Lien
1    2021-09-01 00:59:59.982     Conventional:First Lien
2    2021-08-30 15:51:20.402     Conventional:First Lien
3    2021-09-15 11:11:22.061     Conventional:First Lien
4    2021-09-20 04:50:24.776     Conventional:First Lien
...                      ...                         ...
5362 2021-09-20 22:48:28.670     Conventional:First Lien
5363 2021-08-30 12:06:55.006     Conventional:First Lien
5364 2021-09-10 04:10:35.374     Conventional:First Lien
5365 2021-09-06 00:00:00.000     Conventional:First Lien
5366 2021-09-06 06:35:03.088     Conventional:First Lien

[5367 rows x 2 columns]
Columns file_in_audit and derived_dwelling_category_y are different.
Differences found in columns file_in_audit and derived_dwelling_category_y:
               file_in_audit           derived_dwelling_category_y
0    2021-09-07 00:01:28.091  Single Family (1-4 Units):Site-Built
1    2021-09-01 00:59:59.982  Single Family (1-4 Units):Site-Built
2    2021-08-30 15:51:20.402  Single Family (1-4 Units):Site-Built
3    2021-09-15 11:11:22.061  Single Family (1-4 Units):Site-Built
4    2021-09-20 04:50:24.776  Single Family (1-4 Units):Site-Built
...                      ...                                   ...
5362 2021-09-20 22:48:28.670  Single Family (1-4 Units):Site-Built
5363 2021-08-30 12:06:55.006  Single Family (1-4 Units):Site-Built
5364 2021-09-10 04:10:35.374  Single Family (1-4 Units):Site-Built
5365 2021-09-06 00:00:00.000  Single Family (1-4 Units):Site-Built
5366 2021-09-06 06:35:03.088  Single Family (1-4 Units):Site-Built

[5367 rows x 2 columns]
Columns file_in_audit and loan_type_y are different.
Differences found in columns file_in_audit and loan_type_y:
               file_in_audit   loan_type_y
0    2021-09-07 00:01:28.091  Conventional
1    2021-09-01 00:59:59.982  Conventional
2    2021-08-30 15:51:20.402  Conventional
3    2021-09-15 11:11:22.061  Conventional
4    2021-09-20 04:50:24.776  Conventional
...                      ...           ...
5362 2021-09-20 22:48:28.670  Conventional
5363 2021-08-30 12:06:55.006  Conventional

In [ ]:
df_reduced=merged_data

In [ ]:
df_reduced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 63 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   loan_id                      5367 non-null   int64
 1   loan_amount_x                5367 non-null   int64
 2   first_payment_date_x         5367 non-null   datetime64[ns]
 3   principal_interest_payment   5367 non-null   float64
 4   interest_rate_x              5367 non-null   float64
 5   loan_term_x                  5367 non-null   int64
 6   next_payment_due_date        5367 non-null   datetime64[ns]
 7   payment_periods_made         5367 non-null   int64
 8   current_balance              5367 non-null   float64
 9   loan_status                  5367 non-null   object
 10  amortized_balance            5367 non-null   float64
 11  golden_sachs                 5367 non-null   float64
 12  storgan_manley               5367 non-null   float64
 13  smells_largo                 5367 non-null   float64
 14  bank_of_americans            5367 non-null   float64
 15  pj_logan                     5367 non-null   float64
 16  state_code_x                 5367 non-null   object
 17  county_x                     5367 non-null   object
 18  conforming_loan_limit_x      5367 non-null   bool
 19  derived_loan_product_type_x  5367 non-null   object
 20  derived_dwelling_category_x  5367 non-null   object
 21  loan_type_x                  5367 non-null   object
 22  loan_purpose_x               5367 non-null   object
 23  lien_position_x              5367 non-null   int64
 24  reverse_mortgage_x           5367 non-null   bool
 25  open-end_line_of_credit_x    5367 non-null   bool
 26  closing_date_x               5367 non-null   datetime64[ns]
 27  maturity_date_x              5367 non-null   datetime64[ns]
 28  principal_interest_pmt_x     5367 non-null   float64
 29  interest_rate_y              5367 non-null   float64
 30  property_value_x             5367 non-null   int64
 31  total_loan_costs_x           5365 non-null   float64
 32  origition_charges_x          5367 non-null   float64
 33  other_loan_costs_x           5367 non-null   object
 34  lender_credits_x             39 non-null     object
 35  prepayment_pelty_term_x      0 non-null      float64
 36  intro_rate_period_x          85 non-null     float64
 37  interest_only_payment_x      5367 non-null   int64
 38  occupancy_type_x             5367 non-null   object
 39  total_units_x                5367 non-null   int64
 40  income_thousands_x           5367 non-null   object
 41  recurring_monthly_debt_x     5340 non-null   float64
 42  median_fico_score_x          5367 non-null   int64
 43  credit_score_type_x          5367 non-null   object
 44  aus_type_x                   5304 non-null   object
 45  umbs_code_x                  5367 non-null   object
 46  target_profit_x              5367 non-null   float64
 47  file_in_audit                5114 non-null   datetime64[ns]
 48  file_audit_complete          4591 non-null   datetime64[ns]
 49  file_sent_to_custodian       4207 non-null   datetime64[ns]
 50  file_at_custodian            3244 non-null   datetime64[ns]
 51  base_margin                  5367 non-null   float64
 52  umbs price                   5367 non-null   float64
 53  trade_margin                 5367 non-null   float64
 54  Trade Premium                5367 non-null   float64
 55  Total Loan Revenue           5367 non-null   float64
 56  Gross Profit                 5365 non-null   float64
 57  Profit Margin                5365 non-null   float64
 58  Winning Bid                  5367 non-null   float64
 59  Winner                       5367 non-null   object
 60  actual trade premium         5367 non-null   float64
 61  acctual loan revenue         1467 non-null   float64
 62  actual profit margin         1467 non-null   float64
dtypes: bool(3), datetime64[ns](8), float64(28), int64(9), object(15)
memory usage: 2.5+ MB

In [ ]:
# Rename the remaining _x columns by removing the suffix
df_reduced.columns = [col[:-2] if col.endswith('_x') else col for col in df_reduced.columns]

In [ ]:

df_reduced

,loan_id,loan_amount,first_payment_date,principal_interest_payment,interest_rate,loan_term,next_payment_due_date,payment_periods_made,current_balance,loan_status,amortized_balance,golden_sachs,storgan_manley,smells_largo,bank_of_americans,pj_logan,state_code,county,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,loan_type,loan_purpose,lien_position,reverse_mortgage,open-end_line_of_credit,closing_date,maturity_date,principal_interest_pmt,interest_rate_y,property_value,total_loan_costs,origition_charges,other_loan_costs,lender_credits,prepayment_pelty_term,intro_rate_period,interest_only_payment,occupancy_type,total_units,income_thousands,recurring_monthly_debt,median_fico_score,credit_score_type,aus_type,umbs_code,target_profit,file_in_audit,file_audit_complete,file_sent_to_custodian,file_at_custodian,base_margin,umbs price,trade_margin,Trade Premium,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,acctual loan revenue,actual profit margin
0,5021364,375000,2021-10-01,1632.03,0.03250,360,2021-10-01,0,375000.0,Delinquent,1.502453e-07,102.75000,102.78125,102.84375,102.81250,102.71875,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-03,2051-09-01,1627.62,3.250,500067,3104.50,0.0,3104.5,NaN,NaN,NaN,0,Investment property,1,147,5145.0,650,Experian Fair Isaac,LP,UMBS 15YR 3.0,18750.0,2021-09-07 00:01:28.091,2021-09-13 10:23:25.842,2021-09-13 08:51:00.030,2021-09-15 08:51:00.030,1.05,105.00,0.0500,18750.0,18750.0,18750.0,0.05,0.050000,umbs_price,18750.0000,NaN,NaN
1,5021367,545000,2021-10-01,2822.06,0.02250,240,2021-10-01,0,545000.0,Delinquent,-1.267486e-06,0.00000,0.00000,0.00000,0.00000,0.00000,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-27,2041-09-01,2816.78,2.250,993257,10736.50,10736.5,0,NaN,NaN,NaN,0,Primary residence,1,108,4230.0,620,Equifax Beacon 5.0,LP,UMBS 15YR 2.0,27250.0,2021-09-01 00:59:59.982,2021-09-03 00:59:59.982,2021-09-06 00:59:59.982,2021-09-08 00:59:59.982,1.05,103.03,0.0303,16513.5,27250.0,27250.0,0.05,0.030300,umbs_price,16513.5000,NaN,NaN
2,5021369,325000,2021-10-01,1368.47,0.02990,360,2021-10-01,0,325000.0,Delinquent,-9.163703e-07,100.87750,100.84625,100.84625,100.81500,100.84625,TX,Travis,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-21,2051-09-01,1365.06,2.990,651303,8183.75,5882.5,2301.25,NaN,NaN,NaN,0,Primary residence,1,362,5732.0,643,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,16250.0,2021-08-30 15:51:20.402,2021-08-31 15:51:20.402,2021-09-01 15:51:20.402,2021-09-03 15:51:20.402,1.05,103.19,0.0319,10367.5,16250.0,16250.0,0.05,0.031900,umbs_price,10367.5000,NaN,NaN
3,5021371,265000,2021-10-01,1099.47,0.02875,360,2021-10-01,0,265000.0,Delinquent,-1.029699e-06,101.06500,101.09625,101.15875,101.12750,100.90875,CA,Fresno,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-13,2051-09-01,1096.84,2.875,1257713,6814.75,4796.5,2018.25,NaN,NaN,NaN,0,Second residence,1,127,4869.0,655,FICO Risk Score Classic,LP,UMBS 30YR 2.5,13250.0,2021-09-15 11:11:22.061,2021-09-17 11:11:22.061,2021-09-20 11:11:22.061,NaT,1.05,103.19,0.0319,8453.5,13250.0,13250.0,0.05,0.031900,umbs_price,8453.5000,NaN,NaN
4,5021372,295000,2021-11-01,1304.19,0.03375,360,2021-11-01,0,295000.0,Delinquent,4.787354e-07,102.93750,103.03125,103.03125,103.00000,102.78125,NC,Yadkin,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-15,2051-10-01,1300.53,3.375,368750,1834.12,0.0,1834.12,NaN,NaN,NaN,0,Primary residence,1,110,2934.0,655,Equifax Beacon 5.0,DU,UMBS 15YR 3.0,14750.0,2021-09-20 04:50:24.776,2021-09-21 04:50:24.776,NaT,NaT,1.05,105.00,0.0500,14750.0,14750.0,14750.0,0.05,0.050000,umbs_price,14750.0000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5362,5037634,345000,2021-11-01,1501.47,0.03250,360,2021-11-01,0,345000.0,Delinquent,1.381510e-07,102.92250,102.95375,102.89125,102.95375,102.89125,MA,Norfolk,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-15,2051-10-01,1497.41,3.250,689036,3275.00,1345.5,1929.5,NaN,NaN,NaN,0,Primary residence,1,86,2724.0,686,FICO Risk Score Classic,DU,UMBS 30YR 3.0,17250.0,2021-09-20 22:48:28.670,NaT,NaT,NaT,1.05,104.61,0.0461,15904.5,17250.0,17250.0,0.05,0.046100,umbs_price,15904.5000,NaN,NaN
5363,5037636,215000,2021-10-01,905.29,0.02990,360,2021-10-01,0,215000.0,Delinquent,-6.063416e-07,103.40875,103.40875,103.34625,103.34625,103.31500,FL,Osceola,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-24,2051-09-01,903.04,2.990,279730,5728.56,3891.5,1837.06,NaN,NaN,NaN,0,Primary residence,1,58,1982.0,709,Experian Fair Isaac,LP,UMBS 30YR 2.5,10750.0,2021-08-30 12:06:55.006,2021-09-01 05:34:00.024,2021-09-02 05:34:00.024,2021-09-06 05:34:00.024,1.05,103.19,0.0319,6858.5,10750.0,10750.0,0.05,0.034087,golden_sachs,7328.8125,11220.3125,0.052187
5364,5037638,405000,2021-10-01,1705.32,0.02990,360,2021-10-01,0,405000.0,Delinquent,-1.142201e-06,102.90875,102.90875,102.84625,102.84625,102.94000,CA,Santa Barbara,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-07,2051-09-01,1701.08,2.990,772017,9850.00,7330.5,2519.5,NaN,NaN,NaN,0,Primary residence,4,56,2287.0,703,Experian Fair Isaac,LP,UMBS 30YR 2.5,20250.0,2021-09-10 04:10:35.374,2021-09-13 04:10:35.374,2021-09-13 04:10:35.374,2021-09-15 04:10:35.374,1.05,103.19,0.0319,12919.5,20250.0,20250.0,0.05,0.031900,umbs_price,12919.5000,NaN,NaN
5365,5037641,255000,2021-10-01,1057.98,0.02875,360,2021-10-01,0,255000.0,Delinquent,-9.909181e-07,101.56500,101.59625,101.53375,101.56500,101.53375,FL,Miami-Dade,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-02,2051-09-01,1055.45,2.875,400818,5368.82,4615.5,753.32,NaN,NaN,NaN,0,Primary residence,1,110,2934.0,766,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,12750.0,2021-09-06 00:00:00.000,2021-09-06 13:38:01.223,2021-09-07 13:38:01.223,2021-09-09 13:38:01.223,1.05,103.19,0.0319,8134.5,12750.0,12750.0,0.05,0.031900,umbs_price,8134.5000,NaN,NaN
5366,5037646,95000,2021-10-01,420.00,0.03375,360,2021-10-01,0,95000.0,Delinquent,1.542807e-07,105.43750,105.40625,105.34375,105.37500,105.46875,AR,Sebastian,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-02,2051-09-01,418.82,3.375,146538,233.70,0.0,233.7,NaN,NaN,NaN,0,Primary residence,1,65,1571.0,766,Equifax Beacon 5.0,LP,UMBS 15YR 3.0,4750.0,2021-09-06 06:35:03.088,2021-09-08 06:35:03.088,2021-09-09 06:35:03.088,2021-09-13 06:35:03.088,1.05,105.00,0.0500,4750.0,4750.0,4750.0,0.05,0.054688,pj_logan,5195.3125,5195.3125,0.054688

In [ ]:
# Loop through each column and print its name and null count
for column in df_reduced.columns:
    print(f"{column}: {df_reduced[column].isna().sum()}")

loan_id: 0
loan_amount: 0
first_payment_date: 0
principal_interest_payment: 0
interest_rate: 0
loan_term: 0
next_payment_due_date: 0
payment_periods_made: 0
current_balance: 0
loan_status: 0
amortized_balance: 0
golden_sachs: 0
storgan_manley: 0
smells_largo: 0
bank_of_americans: 0
pj_logan: 0
state_code: 0
county: 0
conforming_loan_limit: 0
derived_loan_product_type: 0
derived_dwelling_category: 0
loan_type: 0
loan_purpose: 0
lien_position: 0
reverse_mortgage: 0
open-end_line_of_credit: 0
closing_date: 0
maturity_date: 0
principal_interest_pmt: 0
interest_rate_y: 0
property_value: 0
total_loan_costs: 2
origition_charges: 0
other_loan_costs: 0
lender_credits: 5328
prepayment_pelty_term: 5367
intro_rate_period: 5282
interest_only_payment: 0
occupancy_type: 0
total_units: 0
income_thousands: 0
recurring_monthly_debt: 27
median_fico_score: 0
credit_score_type: 0
aus_type: 63
umbs_code: 0
target_profit: 0
file_in_audit: 253
file_audit_complete: 776
file_sent_to_custodian: 1160
file_at_custodian: 2123
base_margin: 0
umbs price: 0
trade_margin: 0
Trade Premium: 0
Total Loan Revenue: 0
Gross Profit: 2
Profit Margin: 2
Winning Bid: 0
Winner: 0
actual trade premium: 0
acctual loan revenue: 3900
actual profit margin: 3900

rename a column with umbs_price

In [ ]:
# Rename column 'umbs price' to 'umbs_price' in df6
df_reduced.rename(columns={'umbs price': 'umbs_price'}, inplace=True)

let's merge df_reduced with umbs_prices

In [ ]:
df_reduced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 63 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_id                     5367 non-null   int64
 1   loan_amount                 5367 non-null   int64
 2   first_payment_date          5367 non-null   datetime64[ns]
 3   principal_interest_payment  5367 non-null   float64
 4   interest_rate               5367 non-null   float64
 5   loan_term                   5367 non-null   int64
 6   next_payment_due_date       5367 non-null   datetime64[ns]
 7   payment_periods_made        5367 non-null   int64
 8   current_balance             5367 non-null   float64
 9   loan_status                 5367 non-null   object
 10  amortized_balance           5367 non-null   float64
 11  golden_sachs                5367 non-null   float64
 12  storgan_manley              5367 non-null   float64
 13  smells_largo                5367 non-null   float64
 14  bank_of_americans           5367 non-null   float64
 15  pj_logan                    5367 non-null   float64
 16  state_code                  5367 non-null   object
 17  county                      5367 non-null   object
 18  conforming_loan_limit       5367 non-null   bool
 19  derived_loan_product_type   5367 non-null   object
 20  derived_dwelling_category   5367 non-null   object
 21  loan_type                   5367 non-null   object
 22  loan_purpose                5367 non-null   object
 23  lien_position               5367 non-null   int64
 24  reverse_mortgage            5367 non-null   bool
 25  open-end_line_of_credit     5367 non-null   bool
 26  closing_date                5367 non-null   datetime64[ns]
 27  maturity_date               5367 non-null   datetime64[ns]
 28  principal_interest_pmt      5367 non-null   float64
 29  interest_rate_y             5367 non-null   float64
 30  property_value              5367 non-null   int64
 31  total_loan_costs            5365 non-null   float64
 32  origition_charges           5367 non-null   float64
 33  other_loan_costs            5367 non-null   object
 34  lender_credits              39 non-null     object
 35  prepayment_pelty_term       0 non-null      float64
 36  intro_rate_period           85 non-null     float64
 37  interest_only_payment       5367 non-null   int64
 38  occupancy_type              5367 non-null   object
 39  total_units                 5367 non-null   int64
 40  income_thousands            5367 non-null   object
 41  recurring_monthly_debt      5340 non-null   float64
 42  median_fico_score           5367 non-null   int64
 43  credit_score_type           5367 non-null   object
 44  aus_type                    5304 non-null   object
 45  umbs_code                   5367 non-null   object
 46  target_profit               5367 non-null   float64
 47  file_in_audit               5114 non-null   datetime64[ns]
 48  file_audit_complete         4591 non-null   datetime64[ns]
 49  file_sent_to_custodian      4207 non-null   datetime64[ns]
 50  file_at_custodian           3244 non-null   datetime64[ns]
 51  base_margin                 5367 non-null   float64
 52  umbs_price                  5367 non-null   float64
 53  trade_margin                5367 non-null   float64
 54  Trade Premium               5367 non-null   float64
 55  Total Loan Revenue          5367 non-null   float64
 56  Gross Profit                5365 non-null   float64
 57  Profit Margin               5365 non-null   float64
 58  Winning Bid                 5367 non-null   float64
 59  Winner                      5367 non-null   object
 60  actual trade premium        5367 non-null   float64
 61  acctual loan revenue        1467 non-null   float64
 62  actual profit margin        1467 non-null   float64
dtypes: bool(3), datetime64[ns](8), float64(28), int64(9), object(15)
memory usage: 2.5+ MB

In [ ]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   umbs_code    17 non-null     object
 1   umbs_coupon  17 non-null     float64
 2   umbs_term    17 non-null     int64
 3   umbs_price   17 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 672.0+ bytes

identify the common columns between them

In [ ]:
# Convert column names to sets
columns_df_reduced = set(df_reduced.columns)
columns_df6 = set(df6.columns)

# Find common columns across both DataFrames
common_columns = columns_df_reduced & columns_df6

# Display the number of common columns
num_common_columns = common_columns
print("Number of common columns:", common_columns)

Number of common columns: {'umbs_code', 'umbs_price'}

We have an other column umbs price that is also commun

In [ ]:
# Merge df_large with df6 based on 'umbs_code' and 'umbs_price' using 'left' join
final_data = pd.merge(df_reduced, df6, on=['umbs_code', 'umbs_price'], how='left')

In [ ]:
final_data

,loan_id,loan_amount,first_payment_date,principal_interest_payment,interest_rate,loan_term,next_payment_due_date,payment_periods_made,current_balance,loan_status,amortized_balance,golden_sachs,storgan_manley,smells_largo,bank_of_americans,pj_logan,state_code,county,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,loan_type,loan_purpose,lien_position,reverse_mortgage,open-end_line_of_credit,closing_date,maturity_date,principal_interest_pmt,interest_rate_y,property_value,total_loan_costs,origition_charges,other_loan_costs,lender_credits,prepayment_pelty_term,intro_rate_period,interest_only_payment,occupancy_type,total_units,income_thousands,recurring_monthly_debt,median_fico_score,credit_score_type,aus_type,umbs_code,target_profit,file_in_audit,file_audit_complete,file_sent_to_custodian,file_at_custodian,base_margin,umbs_price,trade_margin,Trade Premium,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,acctual loan revenue,actual profit margin,umbs_coupon,umbs_term
0,5021364,375000,2021-10-01,1632.03,0.03250,360,2021-10-01,0,375000.0,Delinquent,1.502453e-07,102.75000,102.78125,102.84375,102.81250,102.71875,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-03,2051-09-01,1627.62,3.250,500067,3104.50,0.0,3104.5,NaN,NaN,NaN,0,Investment property,1,147,5145.0,650,Experian Fair Isaac,LP,UMBS 15YR 3.0,18750.0,2021-09-07 00:01:28.091,2021-09-13 10:23:25.842,2021-09-13 08:51:00.030,2021-09-15 08:51:00.030,1.05,105.00,0.0500,18750.0,18750.0,18750.0,0.05,0.050000,umbs_price,18750.0000,NaN,NaN,3.0,15
1,5021367,545000,2021-10-01,2822.06,0.02250,240,2021-10-01,0,545000.0,Delinquent,-1.267486e-06,0.00000,0.00000,0.00000,0.00000,0.00000,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-27,2041-09-01,2816.78,2.250,993257,10736.50,10736.5,0,NaN,NaN,NaN,0,Primary residence,1,108,4230.0,620,Equifax Beacon 5.0,LP,UMBS 15YR 2.0,27250.0,2021-09-01 00:59:59.982,2021-09-03 00:59:59.982,2021-09-06 00:59:59.982,2021-09-08 00:59:59.982,1.05,103.03,0.0303,16513.5,27250.0,27250.0,0.05,0.030300,umbs_price,16513.5000,NaN,NaN,2.0,15
2,5021369,325000,2021-10-01,1368.47,0.02990,360,2021-10-01,0,325000.0,Delinquent,-9.163703e-07,100.87750,100.84625,100.84625,100.81500,100.84625,TX,Travis,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-21,2051-09-01,1365.06,2.990,651303,8183.75,5882.5,2301.25,NaN,NaN,NaN,0,Primary residence,1,362,5732.0,643,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,16250.0,2021-08-30 15:51:20.402,2021-08-31 15:51:20.402,2021-09-01 15:51:20.402,2021-09-03 15:51:20.402,1.05,103.19,0.0319,10367.5,16250.0,16250.0,0.05,0.031900,umbs_price,10367.5000,NaN,NaN,2.5,30
3,5021371,265000,2021-10-01,1099.47,0.02875,360,2021-10-01,0,265000.0,Delinquent,-1.029699e-06,101.06500,101.09625,101.15875,101.12750,100.90875,CA,Fresno,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-13,2051-09-01,1096.84,2.875,1257713,6814.75,4796.5,2018.25,NaN,NaN,NaN,0,Second residence,1,127,4869.0,655,FICO Risk Score Classic,LP,UMBS 30YR 2.5,13250.0,2021-09-15 11:11:22.061,2021-09-17 11:11:22.061,2021-09-20 11:11:22.061,NaT,1.05,103.19,0.0319,8453.5,13250.0,13250.0,0.05,0.031900,umbs_price,8453.5000,NaN,NaN,2.5,30
4,5021372,295000,2021-11-01,1304.19,0.03375,360,2021-11-01,0,295000.0,Delinquent,4.787354e-07,102.93750,103.03125,103.03125,103.00000,102.78125,NC,Yadkin,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-15,2051-10-01,1300.53,3.375,368750,1834.12,0.0,1834.12,NaN,NaN,NaN,0,Primary residence,1,110,2934.0,655,Equifax Beacon 5.0,DU,UMBS 15YR 3.0,14750.0,2021-09-20 04:50:24.776,2021-09-21 04:50:24.776,NaT,NaT,1.05,105.00,0.0500,14750.0,14750.0,14750.0,0.05,0.050000,umbs_price,14750.0000,NaN,NaN,3.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5362,5037634,345000,2021-11-01,1501.47,0.03250,360,2021-11-01,0,345000.0,Delinquent,1.381510e-07,102.92250,102.95375,102.89125,102.95375,102.89125,MA,Norfolk,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-15,2051-10-01,1497.41,3.250,689036,3275.00,1345.5,1929.5,NaN,NaN,NaN,0,Primary residence,1,86,2724.0,686,FICO Risk Score Classic,DU,UMBS 30YR 3.0,17250.0,2021-09-20 22:48:28.670,NaT,NaT,NaT,1.05,104.61,0.0461,15904.5,17250.0,17250.0,0.05,0.046100,umbs_price,15904.5000,NaN,NaN,3.0,30
5363,5037636,215000,2021-10-01,905.29,0.02990,360,2021-10-01,0,215000.0,Delinquent,-6.063416e-07,103.40875,103.40875,103.34625,103.34625,103.31500,FL,Osceola,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-24,2051-09-01,903.04,2.990,279730,5728.56,3891.5,1837.06,NaN,NaN,NaN,0,Primary residence,1,58,1982.0,709,Experian Fair Isaac,LP,UMBS 30YR 2.5,10750.0,2021-08-30 12:06:55.006,2021-09-01 05:34:00.024,2021-09-02 05:34:00.024,2021-09-06 05:34:00.024,1.05,103.19,0.0319,6858.5,10750.0,10750.0,0.05,0.034087,golden_sachs,7328.8125,11220.3125,0.052187,2.5,30
5364,5037638,405000,2021-10-01,1705.32,0.02990,360,2021-10-01,0,405000.0,Delinquent,-1.142201e-06,102.90875,102.90875,102.84625,102.84625,102.94000,CA,Santa Barbara,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-07,2051-09-01,1701.08,2.990,772017,9850.00,7330.5,2519.5,NaN,NaN,NaN,0,Primary residence,4,56,2287.0,703,Experian Fair Isaac,LP,UMBS 30YR 2.5,20250.0,2021-09-10 04:10:35.374,2021-09-13 04:10:35.374,2021-09-13 04:10:35.374,2021-09-15 04:10:35.374,1.05,103.19,0.0319,12919.5,20250.0,20250.0,0.05,0.031900,umbs_price,12919.5000,NaN,NaN,2.5,30
5365,5037641,255000,2021-10-01,1057.98,0.02875,360,2021-10-01,0,255000.0,Delinquent,-9.909181e-07,101.56500,101.59625,101.53375,101.56500,101.53375,FL,Miami-Dade,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-02,2051-09-01,1055.45,2.875,400818,5368.82,4615.5,753.32,NaN,NaN,NaN,0,Primary residence,1,110,2934.0,766,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,12750.0,2021-09-06 00:00:00.000,2021-09-06 13:38:01.223,2021-09-07 13:38:01.223,2021-09-09 13:38:01.223,1.05,103.19,0.0319,8134.5,12750.0,12750.0,0.05,0.031900,umbs_price,8134.5000,NaN,NaN,2.5,30
5366,5037646,95000,2021-10-01,420.00,0.03375,360,2021-10-01,0,95000.0,Delinquent,1.542807e-07,105.43750,105.40625,105.34375,105.37500,105.46875,AR,Sebastian,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-02,2051-09-01,418.82,3.375,146538,233.70,0.0,233.7,NaN,NaN,NaN,0,Primary residence,1,65,1571.0,766,Equifax Beacon 5.0,LP,UMBS 15YR 3.0,4750.0,2021-09-06 06:35:03.088,2021-09-08 06:35:03.088,2021-09-09 06:35:03.088,2021-09-13 06:35:03.088,1.05,105.00,0.0500,4750.0,4750.0,4750.0,0.05,0.054688,pj_logan,5195.3125,5195.3125,0.054688,3.0,15

In [ ]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_id                     5367 non-null   int64
 1   loan_amount                 5367 non-null   int64
 2   first_payment_date          5367 non-null   datetime64[ns]
 3   principal_interest_payment  5367 non-null   float64
 4   interest_rate               5367 non-null   float64
 5   loan_term                   5367 non-null   int64
 6   next_payment_due_date       5367 non-null   datetime64[ns]
 7   payment_periods_made        5367 non-null   int64
 8   current_balance             5367 non-null   float64
 9   loan_status                 5367 non-null   object
 10  amortized_balance           5367 non-null   float64
 11  golden_sachs                5367 non-null   float64
 12  storgan_manley              5367 non-null   float64
 13  smells_largo                5367 non-null   float64
 14  bank_of_americans           5367 non-null   float64
 15  pj_logan                    5367 non-null   float64
 16  state_code                  5367 non-null   object
 17  county                      5367 non-null   object
 18  conforming_loan_limit       5367 non-null   bool
 19  derived_loan_product_type   5367 non-null   object
 20  derived_dwelling_category   5367 non-null   object
 21  loan_type                   5367 non-null   object
 22  loan_purpose                5367 non-null   object
 23  lien_position               5367 non-null   int64
 24  reverse_mortgage            5367 non-null   bool
 25  open-end_line_of_credit     5367 non-null   bool
 26  closing_date                5367 non-null   datetime64[ns]
 27  maturity_date               5367 non-null   datetime64[ns]
 28  principal_interest_pmt      5367 non-null   float64
 29  interest_rate_y             5367 non-null   float64
 30  property_value              5367 non-null   int64
 31  total_loan_costs            5365 non-null   float64
 32  origition_charges           5367 non-null   float64
 33  other_loan_costs            5367 non-null   object
 34  lender_credits              39 non-null     object
 35  prepayment_pelty_term       0 non-null      float64
 36  intro_rate_period           85 non-null     float64
 37  interest_only_payment       5367 non-null   int64
 38  occupancy_type              5367 non-null   object
 39  total_units                 5367 non-null   int64
 40  income_thousands            5367 non-null   object
 41  recurring_monthly_debt      5340 non-null   float64
 42  median_fico_score           5367 non-null   int64
 43  credit_score_type           5367 non-null   object
 44  aus_type                    5304 non-null   object
 45  umbs_code                   5367 non-null   object
 46  target_profit               5367 non-null   float64
 47  file_in_audit               5114 non-null   datetime64[ns]
 48  file_audit_complete         4591 non-null   datetime64[ns]
 49  file_sent_to_custodian      4207 non-null   datetime64[ns]
 50  file_at_custodian           3244 non-null   datetime64[ns]
 51  base_margin                 5367 non-null   float64
 52  umbs_price                  5367 non-null   float64
 53  trade_margin                5367 non-null   float64
 54  Trade Premium               5367 non-null   float64
 55  Total Loan Revenue          5367 non-null   float64
 56  Gross Profit                5365 non-null   float64
 57  Profit Margin               5365 non-null   float64
 58  Winning Bid                 5367 non-null   float64
 59  Winner                      5367 non-null   object
 60  actual trade premium        5367 non-null   float64
 61  acctual loan revenue        1467 non-null   float64
 62  actual profit margin        1467 non-null   float64
 63  umbs_coupon                 5367 non-null   float64
 64  umbs_term                   5367 non-null   int64
dtypes: bool(3), datetime64[ns](8), float64(29), int64(10), object(15)
memory usage: 2.6+ MB

### Handling missing values

In [ ]:
final_data.isna().sum()

loan_id                          0
loan_amount                      0
first_payment_date               0
principal_interest_payment       0
interest_rate                    0
                              ...
actual trade premium             0
acctual loan revenue          3900
actual profit margin          3900
umbs_coupon                      0
umbs_term                        0
Length: 65, dtype: int64

In [ ]:
# Loop through each column and print its name and null count
for column in final_data.columns:
    print(f"{column}: {final_data[column].isna().sum()}")

loan_id: 0
loan_amount: 0
first_payment_date: 0
principal_interest_payment: 0
interest_rate: 0
loan_term: 0
next_payment_due_date: 0
payment_periods_made: 0
current_balance: 0
loan_status: 0
amortized_balance: 0
golden_sachs: 0
storgan_manley: 0
smells_largo: 0
bank_of_americans: 0
pj_logan: 0
state_code: 0
county: 0
conforming_loan_limit: 0
derived_loan_product_type: 0
derived_dwelling_category: 0
loan_type: 0
loan_purpose: 0
lien_position: 0
reverse_mortgage: 0
open-end_line_of_credit: 0
closing_date: 0
maturity_date: 0
principal_interest_pmt: 0
interest_rate_y: 0
property_value: 0
total_loan_costs: 2
origition_charges: 0
other_loan_costs: 0
lender_credits: 5328
prepayment_pelty_term: 5367
intro_rate_period: 5282
interest_only_payment: 0
occupancy_type: 0
total_units: 0
income_thousands: 0
recurring_monthly_debt: 27
median_fico_score: 0
credit_score_type: 0
aus_type: 63
umbs_code: 0
target_profit: 0
file_in_audit: 253
file_audit_complete: 776
file_sent_to_custodian: 1160
file_at_custodian: 2123
base_margin: 0
umbs_price: 0
trade_margin: 0
Trade Premium: 0
Total Loan Revenue: 0
Gross Profit: 2
Profit Margin: 2
Winning Bid: 0
Winner: 0
actual trade premium: 0
acctual loan revenue: 3900
actual profit margin: 3900
umbs_coupon: 0
umbs_term: 0

we will remove acctual loan revenue, actual profit margin,  prepayment_pelty_term , lender_credits and  intro_rate_period because they contain more than 70% of  null vlaues

In [ ]:
final_data.drop(['acctual loan revenue','actual profit margin','prepayment_pelty_term','intro_rate_period','lender_credits'],axis=1, inplace=True)

In [ ]:
final_data

,loan_id,loan_amount,first_payment_date,principal_interest_payment,interest_rate,loan_term,next_payment_due_date,payment_periods_made,current_balance,loan_status,amortized_balance,golden_sachs,storgan_manley,smells_largo,bank_of_americans,pj_logan,state_code,county,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,loan_type,loan_purpose,lien_position,reverse_mortgage,open-end_line_of_credit,closing_date,maturity_date,principal_interest_pmt,interest_rate_y,property_value,total_loan_costs,origition_charges,other_loan_costs,interest_only_payment,occupancy_type,total_units,income_thousands,recurring_monthly_debt,median_fico_score,credit_score_type,aus_type,umbs_code,target_profit,file_in_audit,file_audit_complete,file_sent_to_custodian,file_at_custodian,base_margin,umbs_price,trade_margin,Trade Premium,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,umbs_coupon,umbs_term
0,5021364,375000,2021-10-01,1632.03,0.03250,360,2021-10-01,0,375000.0,Delinquent,1.502453e-07,102.75000,102.78125,102.84375,102.81250,102.71875,CA,Lake,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-03,2051-09-01,1627.62,3.250,500067,3104.50,0.0,3104.5,0,Investment property,1,147,5145.0,650,Experian Fair Isaac,LP,UMBS 15YR 3.0,18750.0,2021-09-07 00:01:28.091,2021-09-13 10:23:25.842,2021-09-13 08:51:00.030,2021-09-15 08:51:00.030,1.05,105.00,0.0500,18750.0,18750.0,18750.0,0.05,0.050000,umbs_price,18750.0000,3.0,15
1,5021367,545000,2021-10-01,2822.06,0.02250,240,2021-10-01,0,545000.0,Delinquent,-1.267486e-06,0.00000,0.00000,0.00000,0.00000,0.00000,CA,Los Angeles,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-27,2041-09-01,2816.78,2.250,993257,10736.50,10736.5,0,0,Primary residence,1,108,4230.0,620,Equifax Beacon 5.0,LP,UMBS 15YR 2.0,27250.0,2021-09-01 00:59:59.982,2021-09-03 00:59:59.982,2021-09-06 00:59:59.982,2021-09-08 00:59:59.982,1.05,103.03,0.0303,16513.5,27250.0,27250.0,0.05,0.030300,umbs_price,16513.5000,2.0,15
2,5021369,325000,2021-10-01,1368.47,0.02990,360,2021-10-01,0,325000.0,Delinquent,-9.163703e-07,100.87750,100.84625,100.84625,100.81500,100.84625,TX,Travis,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-21,2051-09-01,1365.06,2.990,651303,8183.75,5882.5,2301.2500000000005,0,Primary residence,1,362,5732.0,643,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,16250.0,2021-08-30 15:51:20.402,2021-08-31 15:51:20.402,2021-09-01 15:51:20.402,2021-09-03 15:51:20.402,1.05,103.19,0.0319,10367.5,16250.0,16250.0,0.05,0.031900,umbs_price,10367.5000,2.5,30
3,5021371,265000,2021-10-01,1099.47,0.02875,360,2021-10-01,0,265000.0,Delinquent,-1.029699e-06,101.06500,101.09625,101.15875,101.12750,100.90875,CA,Fresno,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-13,2051-09-01,1096.84,2.875,1257713,6814.75,4796.5,2018.25,0,Second residence,1,127,4869.0,655,FICO Risk Score Classic,LP,UMBS 30YR 2.5,13250.0,2021-09-15 11:11:22.061,2021-09-17 11:11:22.061,2021-09-20 11:11:22.061,NaN,1.05,103.19,0.0319,8453.5,13250.0,13250.0,0.05,0.031900,umbs_price,8453.5000,2.5,30
4,5021372,295000,2021-11-01,1304.19,0.03375,360,2021-11-01,0,295000.0,Delinquent,4.787354e-07,102.93750,103.03125,103.03125,103.00000,102.78125,NC,Yadkin,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-15,2051-10-01,1300.53,3.375,368750,1834.12,0.0,1834.1200000000008,0,Primary residence,1,110,2934.0,655,Equifax Beacon 5.0,DU,UMBS 15YR 3.0,14750.0,2021-09-20 04:50:24.776,2021-09-21 04:50:24.776,NaN,NaN,1.05,105.00,0.0500,14750.0,14750.0,14750.0,0.05,0.050000,umbs_price,14750.0000,3.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5362,5037634,345000,2021-11-01,1501.47,0.03250,360,2021-11-01,0,345000.0,Delinquent,1.381510e-07,102.92250,102.95375,102.89125,102.95375,102.89125,MA,Norfolk,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-15,2051-10-01,1497.41,3.250,689036,3275.00,1345.5,1929.5,0,Primary residence,1,86,2724.0,686,FICO Risk Score Classic,DU,UMBS 30YR 3.0,17250.0,2021-09-20 22:48:28.670,NaN,NaN,NaN,1.05,104.61,0.0461,15904.5,17250.0,17250.0,0.05,0.046100,umbs_price,15904.5000,3.0,30
5363,5037636,215000,2021-10-01,905.29,0.02990,360,2021-10-01,0,215000.0,Delinquent,-6.063416e-07,103.40875,103.40875,103.34625,103.34625,103.31500,FL,Osceola,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-08-24,2051-09-01,903.04,2.990,279730,5728.56,3891.5,1837.0600000000004,0,Primary residence,1,58,1982.0,709,Experian Fair Isaac,LP,UMBS 30YR 2.5,10750.0,2021-08-30 12:06:55.006,2021-09-01 05:34:00.024,2021-09-02 05:34:00.024,2021-09-06 05:34:00.024,1.05,103.19,0.0319,6858.5,10750.0,10750.0,0.05,0.034087,golden_sachs,7328.8125,2.5,30
5364,5037638,405000,2021-10-01,1705.32,0.02990,360,2021-10-01,0,405000.0,Delinquent,-1.142201e-06,102.90875,102.90875,102.84625,102.84625,102.94000,CA,Santa Barbara,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Cash-out refinance,1,False,False,2021-09-07,2051-09-01,1701.08,2.990,772017,9850.00,7330.5,2519.5,0,Primary residence,4,56,2287.0,703,Experian Fair Isaac,LP,UMBS 30YR 2.5,20250.0,2021-09-10 04:10:35.374,2021-09-13 04:10:35.374,2021-09-13 04:10:35.374,2021-09-15 04:10:35.374,1.05,103.19,0.0319,12919.5,20250.0,20250.0,0.05,0.031900,umbs_price,12919.5000,2.5,30
5365,5037641,255000,2021-10-01,1057.98,0.02875,360,2021-10-01,0,255000.0,Delinquent,-9.909181e-07,101.56500,101.59625,101.53375,101.56500,101.53375,FL,Miami-Dade,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-02,2051-09-01,1055.45,2.875,400818,5368.82,4615.5,753.3199999999999,0,Primary residence,1,110,2934.0,766,Equifax Beacon 5.0,LP,UMBS 30YR 2.5,12750.0,2021-09-06 00:00:00.000,2021-09-06 13:38:01.223,2021-09-07 13:38:01.223,2021-09-09 13:38:01.223,1.05,103.19,0.0319,8134.5,12750.0,12750.0,0.05,0.031900,umbs_price,8134.5000,2.5,30
5366,5037646,95000,2021-10-01,420.00,0.03375,360,2021-10-01,0,95000.0,Delinquent,1.542807e-07,105.43750,105.40625,105.34375,105.37500,105.46875,AR,Sebastian,True,Conventional:First Lien,Single Family (1-4 Units):Site-Built,Conventional,Refinancing,1,False,False,2021-09-02,2051-09-01,418.82,3.375,146538,233.70,0.0,233.69999999999982,0,Primary residence,1,65,1571.0,766,Equifax Beacon 5.0,LP,UMBS 15YR 3.0,4750.0,2021-09-06 06:35:03.088,2021-09-08 06:35:03.088,2021-09-09 06:35:03.088,2021-09-13 06:35:03.088,1.05,105.00,0.0500,4750.0,4750.0,4750.0,0.05,0.054688,pj_logan,5195.3125,3.0,15

In [ ]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5367 entries, 0 to 5366
Data columns (total 60 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_id                     5367 non-null   int64
 1   loan_amount                 5367 non-null   int64
 2   first_payment_date          5367 non-null   object
 3   principal_interest_payment  5367 non-null   float64
 4   interest_rate               5367 non-null   float64
 5   loan_term                   5367 non-null   int64
 6   next_payment_due_date       5367 non-null   object
 7   payment_periods_made        5367 non-null   int64
 8   current_balance             5367 non-null   float64
 9   loan_status                 5367 non-null   object
 10  amortized_balance           5367 non-null   float64
 11  golden_sachs                5367 non-null   float64
 12  storgan_manley              5367 non-null   float64
 13  smells_largo                5367 non-null   float64
 14  bank_of_americans           5367 non-null   float64
 15  pj_logan                    5367 non-null   float64
 16  state_code                  5367 non-null   object
 17  county                      5367 non-null   object
 18  conforming_loan_limit       5367 non-null   bool
 19  derived_loan_product_type   5367 non-null   object
 20  derived_dwelling_category   5367 non-null   object
 21  loan_type                   5367 non-null   object
 22  loan_purpose                5367 non-null   object
 23  lien_position               5367 non-null   int64
 24  reverse_mortgage            5367 non-null   bool
 25  open-end_line_of_credit     5367 non-null   bool
 26  closing_date                5367 non-null   object
 27  maturity_date               5367 non-null   object
 28  principal_interest_pmt      5367 non-null   float64
 29  interest_rate_y             5367 non-null   float64
 30  property_value              5367 non-null   int64
 31  total_loan_costs            5365 non-null   float64
 32  origition_charges           5367 non-null   float64
 33  other_loan_costs            5367 non-null   object
 34  interest_only_payment       5367 non-null   int64
 35  occupancy_type              5367 non-null   object
 36  total_units                 5367 non-null   int64
 37  income_thousands            5367 non-null   object
 38  recurring_monthly_debt      5340 non-null   float64
 39  median_fico_score           5367 non-null   int64
 40  credit_score_type           5367 non-null   object
 41  aus_type                    5304 non-null   object
 42  umbs_code                   5367 non-null   object
 43  target_profit               5367 non-null   float64
 44  file_in_audit               5114 non-null   object
 45  file_audit_complete         4591 non-null   object
 46  file_sent_to_custodian      4207 non-null   object
 47  file_at_custodian           3244 non-null   object
 48  base_margin                 5367 non-null   float64
 49  umbs_price                  5367 non-null   float64
 50  trade_margin                5367 non-null   float64
 51  Trade Premium               5367 non-null   float64
 52  Total Loan Revenue          5367 non-null   float64
 53  Gross Profit                5365 non-null   float64
 54  Profit Margin               5365 non-null   float64
 55  Winning Bid                 5367 non-null   float64
 56  Winner                      5367 non-null   object
 57  actual trade premium        5367 non-null   float64
 58  umbs_coupon                 5367 non-null   float64
 59  umbs_term                   5367 non-null   int64
dtypes: bool(3), float64(25), int64(10), object(22)
memory usage: 2.3+ MB

In [ ]:
# Identify columns with any null values
columns_with_nulls = final_data.columns[final_data.isnull().any()]

# Extract these columns
df_with_nulls = final_data[columns_with_nulls]

In [ ]:
df_with_nulls

,total_loan_costs,recurring_monthly_debt,aus_type,file_in_audit,file_audit_complete,file_sent_to_custodian,file_at_custodian,Gross Profit,Profit Margin
0,3104.50,5145.0,LP,2021-09-07 00:01:28.091,2021-09-13 10:23:25.842,2021-09-13 08:51:00.030,2021-09-15 08:51:00.030,18750.0,0.05
1,10736.50,4230.0,LP,2021-09-01 00:59:59.982,2021-09-03 00:59:59.982,2021-09-06 00:59:59.982,2021-09-08 00:59:59.982,27250.0,0.05
2,8183.75,5732.0,LP,2021-08-30 15:51:20.402,2021-08-31 15:51:20.402,2021-09-01 15:51:20.402,2021-09-03 15:51:20.402,16250.0,0.05
3,6814.75,4869.0,LP,2021-09-15 11:11:22.061,2021-09-17 11:11:22.061,2021-09-20 11:11:22.061,NaN,13250.0,0.05
4,1834.12,2934.0,DU,2021-09-20 04:50:24.776,2021-09-21 04:50:24.776,NaN,NaN,14750.0,0.05
...,...,...,...,...,...,...,...,...,...
5362,3275.00,2724.0,DU,2021-09-20 22:48:28.670,NaN,NaN,NaN,17250.0,0.05
5363,5728.56,1982.0,LP,2021-08-30 12:06:55.006,2021-09-01 05:34:00.024,2021-09-02 05:34:00.024,2021-09-06 05:34:00.024,10750.0,0.05
5364,9850.00,2287.0,LP,2021-09-10 04:10:35.374,2021-09-13 04:10:35.374,2021-09-13 04:10:35.374,2021-09-15 04:10:35.374,20250.0,0.05
5365,5368.82,2934.0,LP,2021-09-06 00:00:00.000,2021-09-06 13:38:01.223,2021-09-07 13:38:01.223,2021-09-09 13:38:01.223,12750.0,0.05
5366,233.70,1571.0,LP,2021-09-06 06:35:03.088,2021-09-08 06:35:03.088,2021-09-09 06:35:03.088,2021-09-13 06:35:03.088,4750.0,0.05

In [ ]:
percent_nulls = df_with_nulls.isnull().mean() * 100

In [ ]:
percent_nulls

total_loan_costs           0.037265
recurring_monthly_debt     0.503074
aus_type                   1.173840
file_in_audit              4.713993
file_audit_complete       14.458729
file_sent_to_custodian    21.613564
file_at_custodian         39.556549
Gross Profit               0.037265
Profit Margin              0.037265
dtype: float64

In [ ]:
df_with_nulls.dtypes

total_loan_costs          float64
recurring_monthly_debt    float64
aus_type                   object
file_in_audit              object
file_audit_complete        object
file_sent_to_custodian     object
file_at_custodian          object
Gross Profit              float64
Profit Margin             float64
dtype: object

In [ ]:
df_with_nulls[['total_loan_costs','recurring_monthly_debt','Gross Profit','Profit Margin']].describe()

       total_loan_costs  recurring_monthly_debt  Gross Profit  Profit Margin
count       5365.000000             5340.000000   5365.000000    5365.000000
mean        7644.291167             3114.159176  14144.777021       0.049971
std         7203.306692             2056.849884   8457.677856       0.000476
min       -13323.950000              310.000000   2750.000000       0.035303
25%         3166.000000             1740.000000   8250.000000       0.050000
50%         5417.500000             2634.500000  12250.000000       0.050000
75%         9481.000000             3850.000000  17750.000000       0.050000
max        81663.000000            20070.000000  89750.000000       0.050000

Let's fill the null values on numerc data with the mean

In [ ]:
# Fill null values in each column with the mean of that column
final_data['total_loan_costs'].fillna(final_data['total_loan_costs'].mean(), inplace=True)
final_data['recurring_monthly_debt'].fillna(final_data['recurring_monthly_debt'].mean(), inplace=True)
final_data['Gross Profit'].fillna(final_data['Gross Profit'].mean(), inplace=True)
final_data['Profit Margin'].fillna(final_data['Profit Margin'].mean(), inplace=True)

In [ ]:
final_data.isna().sum()

loan_id                          0
loan_amount                      0
first_payment_date               0
principal_interest_payment       0
interest_rate                    0
loan_term                        0
next_payment_due_date            0
payment_periods_made             0
current_balance                  0
loan_status                      0
amortized_balance                0
golden_sachs                     0
storgan_manley                   0
smells_largo                     0
bank_of_americans                0
pj_logan                         0
state_code                       0
county                           0
conforming_loan_limit            0
derived_loan_product_type        0
derived_dwelling_category        0
loan_type                        0
loan_purpose                     0
lien_position                    0
reverse_mortgage                 0
open-end_line_of_credit          0
closing_date                     0
maturity_date                    0
principal_interest_pmt           0
interest_rate_y                  0
property_value                   0
total_loan_costs                 0
origition_charges                0
other_loan_costs                 0
interest_only_payment            0
occupancy_type                   0
total_units                      0
income_thousands                 0
recurring_monthly_debt           0
median_fico_score                0
credit_score_type                0
aus_type                        63
umbs_code                        0
target_profit                    0
file_in_audit                  253
file_audit_complete            776
file_sent_to_custodian        1160
file_at_custodian             2123
base_margin                      0
umbs_price                       0
trade_margin                     0
Trade Premium                    0
Total Loan Revenue               0
Gross Profit                     0
Profit Margin                    0
Winning Bid                      0
Winner                           0
actual trade premium             0
umbs_coupon                      0
umbs_term                        0
dtype: int64

In [ ]:
df_with_nulls[['aus_type','file_in_audit','file_audit_complete','file_sent_to_custodian','file_at_custodian']].describe()

,aus_type,file_in_audit,file_audit_complete,file_sent_to_custodian,file_at_custodian
count,5304,5114,4591,4207,3244
unique,2,4260,4169,4013,3113
top,DU,2021-09-06 00:00:00.000,2021-09-20 00:00:00.000,2021-09-20 00:00:00.000,2021-09-08 00:00:00.000
freq,3740,167,89,54,22

Fill null values with the most frequent category (mode)

In [ ]:
final_data['aus_type'].fillna('Unknown', inplace=True)
final_data['file_in_audit'].fillna(final_data['file_in_audit'].mode()[0], inplace=True)
final_data['file_audit_complete'].fillna(final_data['file_audit_complete'].mode()[0], inplace=True)
final_data['file_sent_to_custodian'].fillna(final_data['file_sent_to_custodian'].mode()[0], inplace=True)
final_data['file_at_custodian'].fillna(final_data['file_at_custodian'].mode()[0], inplace=True)

In [ ]:
final_data.isna().sum()

loan_id                       0
loan_amount                   0
first_payment_date            0
principal_interest_payment    0
interest_rate                 0
loan_term                     0
next_payment_due_date         0
payment_periods_made          0
current_balance               0
loan_status                   0
amortized_balance             0
golden_sachs                  0
storgan_manley                0
smells_largo                  0
bank_of_americans             0
pj_logan                      0
state_code                    0
county                        0
conforming_loan_limit         0
derived_loan_product_type     0
derived_dwelling_category     0
loan_type                     0
loan_purpose                  0
lien_position                 0
reverse_mortgage              0
open-end_line_of_credit       0
closing_date                  0
maturity_date                 0
principal_interest_pmt        0
interest_rate_y               0
property_value                0
total_loan_costs              0
origition_charges             0
other_loan_costs              0
interest_only_payment         0
occupancy_type                0
total_units                   0
income_thousands              0
recurring_monthly_debt        0
median_fico_score             0
credit_score_type             0
aus_type                      0
umbs_code                     0
target_profit                 0
file_in_audit                 0
file_audit_complete           0
file_sent_to_custodian        0
file_at_custodian             0
base_margin                   0
umbs_price                    0
trade_margin                  0
Trade Premium                 0
Total Loan Revenue            0
Gross Profit                  0
Profit Margin                 0
Winning Bid                   0
Winner                        0
actual trade premium          0
umbs_coupon                   0
umbs_term                     0
dtype: int64

In [ ]:
final_data.to_csv(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/finaldata.csv')

In [ ]:
final_data=pd.read_csv(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/finaldata.csv')

In [ ]:
final_data

,Unnamed: 0,loan_id,loan_amount,first_payment_date,principal_interest_payment,interest_rate,loan_term,next_payment_due_date,payment_periods_made,current_balance,...,trade_margin,Trade Premium,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,umbs_coupon,umbs_term
0,0,5021364,375000,2021-10-01,1632.03,0.03250,360,2021-10-01,0,375000.0,...,0.0500,18750.0,18750.0,18750.0,0.05,0.050000,umbs_price,18750.0000,3.0,15
1,1,5021367,545000,2021-10-01,2822.06,0.02250,240,2021-10-01,0,545000.0,...,0.0303,16513.5,27250.0,27250.0,0.05,0.030300,umbs_price,16513.5000,2.0,15
2,2,5021369,325000,2021-10-01,1368.47,0.02990,360,2021-10-01,0,325000.0,...,0.0319,10367.5,16250.0,16250.0,0.05,0.031900,umbs_price,10367.5000,2.5,30
3,3,5021371,265000,2021-10-01,1099.47,0.02875,360,2021-10-01,0,265000.0,...,0.0319,8453.5,13250.0,13250.0,0.05,0.031900,umbs_price,8453.5000,2.5,30
4,4,5021372,295000,2021-11-01,1304.19,0.03375,360,2021-11-01,0,295000.0,...,0.0500,14750.0,14750.0,14750.0,0.05,0.050000,umbs_price,14750.0000,3.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5362,5362,5037634,345000,2021-11-01,1501.47,0.03250,360,2021-11-01,0,345000.0,...,0.0461,15904.5,17250.0,17250.0,0.05,0.046100,umbs_price,15904.5000,3.0,30
5363,5363,5037636,215000,2021-10-01,905.29,0.02990,360,2021-10-01,0,215000.0,...,0.0319,6858.5,10750.0,10750.0,0.05,0.034087,golden_sachs,7328.8125,2.5,30
5364,5364,5037638,405000,2021-10-01,1705.32,0.02990,360,2021-10-01,0,405000.0,...,0.0319,12919.5,20250.0,20250.0,0.05,0.031900,umbs_price,12919.5000,2.5,30
5365,5365,5037641,255000,2021-10-01,1057.98,0.02875,360,2021-10-01,0,255000.0,...,0.0319,8134.5,12750.0,12750.0,0.05,0.031900,umbs_price,8134.5000,2.5,30
5366,5366,5037646,95000,2021-10-01,420.00,0.03375,360,2021-10-01,0,95000.0,...,0.0500,4750.0,4750.0,4750.0,0.05,0.054688,pj_logan,5195.3125,3.0,15

In [ ]:
final_data.drop('Unnamed: 0',inplace=True,axis=1)

In [ ]:
final_data

,loan_id,loan_amount,first_payment_date,principal_interest_payment,interest_rate,loan_term,next_payment_due_date,payment_periods_made,current_balance,loan_status,...,trade_margin,Trade Premium,Total Loan Revenue,Gross Profit,Profit Margin,Winning Bid,Winner,actual trade premium,umbs_coupon,umbs_term
0,5021364,375000,2021-10-01,1632.03,0.03250,360,2021-10-01,0,375000.0,Delinquent,...,0.0500,18750.0,18750.0,18750.0,0.05,0.050000,umbs_price,18750.0000,3.0,15
1,5021367,545000,2021-10-01,2822.06,0.02250,240,2021-10-01,0,545000.0,Delinquent,...,0.0303,16513.5,27250.0,27250.0,0.05,0.030300,umbs_price,16513.5000,2.0,15
2,5021369,325000,2021-10-01,1368.47,0.02990,360,2021-10-01,0,325000.0,Delinquent,...,0.0319,10367.5,16250.0,16250.0,0.05,0.031900,umbs_price,10367.5000,2.5,30
3,5021371,265000,2021-10-01,1099.47,0.02875,360,2021-10-01,0,265000.0,Delinquent,...,0.0319,8453.5,13250.0,13250.0,0.05,0.031900,umbs_price,8453.5000,2.5,30
4,5021372,295000,2021-11-01,1304.19,0.03375,360,2021-11-01,0,295000.0,Delinquent,...,0.0500,14750.0,14750.0,14750.0,0.05,0.050000,umbs_price,14750.0000,3.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5362,5037634,345000,2021-11-01,1501.47,0.03250,360,2021-11-01,0,345000.0,Delinquent,...,0.0461,15904.5,17250.0,17250.0,0.05,0.046100,umbs_price,15904.5000,3.0,30
5363,5037636,215000,2021-10-01,905.29,0.02990,360,2021-10-01,0,215000.0,Delinquent,...,0.0319,6858.5,10750.0,10750.0,0.05,0.034087,golden_sachs,7328.8125,2.5,30
5364,5037638,405000,2021-10-01,1705.32,0.02990,360,2021-10-01,0,405000.0,Delinquent,...,0.0319,12919.5,20250.0,20250.0,0.05,0.031900,umbs_price,12919.5000,2.5,30
5365,5037641,255000,2021-10-01,1057.98,0.02875,360,2021-10-01,0,255000.0,Delinquent,...,0.0319,8134.5,12750.0,12750.0,0.05,0.031900,umbs_price,8134.5000,2.5,30
5366,5037646,95000,2021-10-01,420.00,0.03375,360,2021-10-01,0,95000.0,Delinquent,...,0.0500,4750.0,4750.0,4750.0,0.05,0.054688,pj_logan,5195.3125,3.0,15

Check data types

In [ ]:
final_data.dtypes

loan_id                         int64
loan_amount                     int64
first_payment_date             object
principal_interest_payment    float64
interest_rate                 float64
loan_term                       int64
next_payment_due_date          object
payment_periods_made            int64
current_balance               float64
loan_status                    object
amortized_balance             float64
golden_sachs                  float64
storgan_manley                float64
smells_largo                  float64
bank_of_americans             float64
pj_logan                      float64
state_code                     object
county                         object
conforming_loan_limit            bool
derived_loan_product_type      object
derived_dwelling_category      object
loan_type                      object
loan_purpose                   object
lien_position                   int64
reverse_mortgage                 bool
open-end_line_of_credit          bool
closing_date                   object
maturity_date                  object
principal_interest_pmt        float64
interest_rate_y               float64
property_value                  int64
total_loan_costs              float64
origition_charges             float64
other_loan_costs               object
interest_only_payment           int64
occupancy_type                 object
total_units                     int64
income_thousands               object
recurring_monthly_debt        float64
median_fico_score               int64
credit_score_type              object
aus_type                       object
umbs_code                      object
target_profit                 float64
file_in_audit                  object
file_audit_complete            object
file_sent_to_custodian         object
file_at_custodian              object
base_margin                   float64
umbs_price                    float64
trade_margin                  float64
Trade Premium                 float64
Total Loan Revenue            float64
Gross Profit                  float64
Profit Margin                 float64
Winning Bid                   float64
Winner                         object
actual trade premium          float64
umbs_coupon                   float64
umbs_term                       int64
dtype: object

In [ ]:
final_data['first_payment_date'] = pd.to_datetime(final_data['first_payment_date'])
final_data['next_payment_due_date'] = pd.to_datetime(final_data['next_payment_due_date'])
final_data['loan_status'] = final_data['loan_status'].astype(str)
final_data['state_code'] = final_data['state_code'].astype(str)
final_data['county'] = final_data['county'].astype(str)
final_data['derived_loan_product_type'] = final_data['derived_loan_product_type'].astype(str)
final_data['derived_dwelling_category'] = final_data['derived_dwelling_category'].astype(str)
final_data['loan_type'] = final_data['loan_type'].astype(str)
final_data['loan_purpose'] = final_data['loan_purpose'].astype(str)
final_data['closing_date'] = pd.to_datetime(final_data['closing_date'])
final_data['maturity_date'] = pd.to_datetime(final_data['maturity_date'])
final_data['occupancy_type'] = final_data['occupancy_type'].astype(str)
final_data['income_thousands'] = pd.to_numeric(final_data['income_thousands'], errors='coerce')
final_data['credit_score_type'] = final_data['credit_score_type'].astype(str)
final_data['aus_type'] = final_data['aus_type'].astype(str)
final_data['umbs_code'] = final_data['umbs_code'].astype(str)
final_data['file_in_audit'] = pd.to_datetime(final_data['file_in_audit'])
final_data['file_audit_complete'] = pd.to_datetime(final_data['file_audit_complete'])
final_data['file_sent_to_custodian'] = pd.to_datetime(final_data['file_sent_to_custodian'])
final_data['file_at_custodian'] = pd.to_datetime(final_data['file_at_custodian'])
final_data['Winner'] = final_data['Winner'].astype(str)

In [ ]:
final_data['other_loan_costs'] = pd.to_numeric(final_data['other_loan_costs'], errors='coerce')

In [ ]:
final_data.dtypes

loan_id                                int64
loan_amount                            int64
first_payment_date            datetime64[ns]
principal_interest_payment           float64
interest_rate                        float64
loan_term                              int64
next_payment_due_date         datetime64[ns]
payment_periods_made                   int64
current_balance                      float64
loan_status                           object
amortized_balance                    float64
golden_sachs                         float64
storgan_manley                       float64
smells_largo                         float64
bank_of_americans                    float64
pj_logan                             float64
state_code                            object
county                                object
conforming_loan_limit                   bool
derived_loan_product_type             object
derived_dwelling_category             object
loan_type                             object
loan_purpose                          object
lien_position                          int64
reverse_mortgage                        bool
open-end_line_of_credit                 bool
closing_date                  datetime64[ns]
maturity_date                 datetime64[ns]
principal_interest_pmt               float64
interest_rate_y                      float64
property_value                         int64
total_loan_costs                     float64
origition_charges                    float64
other_loan_costs                     float64
interest_only_payment                  int64
occupancy_type                        object
total_units                            int64
income_thousands                     float64
recurring_monthly_debt               float64
median_fico_score                      int64
credit_score_type                     object
aus_type                              object
umbs_code                             object
target_profit                        float64
file_in_audit                 datetime64[ns]
file_audit_complete           datetime64[ns]
file_sent_to_custodian        datetime64[ns]
file_at_custodian             datetime64[ns]
base_margin                          float64
umbs_price                           float64
trade_margin                         float64
Trade Premium                        float64
Total Loan Revenue                   float64
Gross Profit                         float64
Profit Margin                        float64
Winning Bid                          float64
Winner                                object
actual trade premium                 float64
umbs_coupon                          float64
umbs_term                              int64
dtype: object

In [ ]:
final_data.to_csv(r'/content/drive/MyDrive/Prepayment-Mortgage-Trading-Analysis-and-Prediction/Datasets/finaldata.csv')